package hibernate;
// Generated 2016-12-8 16:47:11 by Hibernate Tools 5.1.0.Beta1

/**
 * Admin generated by hbm2java
 */
public class Admin implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String userName;
	private String userPwd;
	private String uuid;

	public Admin() {
	}

	public Admin(String userName, String userPwd) {
		this.userName = userName;
		this.userPwd = userPwd;
	}

	public Admin(String userName, String userPwd, String uuid) {
		this.userName = userName;
		this.userPwd = userPwd;
		this.uuid = uuid;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPwd() {
		return this.userPwd;
	}

	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

}
