package hibernate;

// Generated 2016-12-20 16:18:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Approval generated by hbm2java
 */
public class Approval implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String approname;
	private String approtype;
	private Date approtime;
	private String approexp;
	private String approfile;
	private String approperson;
	private String approstate;
	private String judgeperson;
	private String view;

	public Approval() {
	}

	public Approval(String approname, String approtype, Date approtime,
			String approexp, String approfile, String approperson,
			String approstate, String judgeperson, String view) {
		this.approname = approname;
		this.approtype = approtype;
		this.approtime = approtime;
		this.approexp = approexp;
		this.approfile = approfile;
		this.approperson = approperson;
		this.approstate = approstate;
		this.judgeperson = judgeperson;
		this.view = view;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getApproname() {
		return this.approname;
	}

	public void setApproname(String approname) {
		this.approname = approname;
	}

	public String getApprotype() {
		return this.approtype;
	}

	public void setApprotype(String approtype) {
		this.approtype = approtype;
	}

	public Date getApprotime() {
		return this.approtime;
	}

	public void setApprotime(Date approtime) {
		this.approtime = approtime;
	}

	public String getApproexp() {
		return this.approexp;
	}

	public void setApproexp(String approexp) {
		this.approexp = approexp;
	}

	public String getApprofile() {
		return this.approfile;
	}

	public void setApprofile(String approfile) {
		this.approfile = approfile;
	}

	public String getApproperson() {
		return this.approperson;
	}

	public void setApproperson(String approperson) {
		this.approperson = approperson;
	}

	public String getApprostate() {
		return this.approstate;
	}

	public void setApprostate(String approstate) {
		this.approstate = approstate;
	}

	public String getJudgeperson() {
		return this.judgeperson;
	}

	public void setJudgeperson(String judgeperson) {
		this.judgeperson = judgeperson;
	}

	public String getView() {
		return this.view;
	}

	public void setView(String view) {
		this.view = view;
	}

}
