package hibernate;
// Generated 2017-4-13 17:12:05 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * Commonlaw generated by hbm2java
 */
public class Commonlaw implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String no;
	private String name;
	private String fromUnit;
	private Date applyDate;
	private Date enactDate;
	private String accessory;
	private String type;

	public Commonlaw() {
	}

	public Commonlaw(String no, String name, String fromUnit, Date applyDate, Date enactDate, String accessory,
			String type) {
		this.no = no;
		this.name = name;
		this.fromUnit = fromUnit;
		this.applyDate = applyDate;
		this.enactDate = enactDate;
		this.accessory = accessory;
		this.type = type;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNo() {
		return this.no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFromUnit() {
		return this.fromUnit;
	}

	public void setFromUnit(String fromUnit) {
		this.fromUnit = fromUnit;
	}

	public Date getApplyDate() {
		return this.applyDate;
	}

	public void setApplyDate(Date applyDate) {
		this.applyDate = applyDate;
	}

	public Date getEnactDate() {
		return this.enactDate;
	}

	public void setEnactDate(Date enactDate) {
		this.enactDate = enactDate;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
