package hibernate;
// Generated 2017-4-13 17:12:05 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * Commonsystem generated by hbm2java
 */
public class Commonsystem implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Date sendDate;
	private Date receiveDate;
	private String no;
	private String name;
	private String fromUnit;
	private String urgency;
	private String requirement;
	private String opinion;
	private String accessory;
	private String type;

	public Commonsystem() {
	}

	public Commonsystem(String no, String name, String fromUnit, String urgency, String requirement, String opinion,
			String accessory, String type) {
		this.no = no;
		this.name = name;
		this.fromUnit = fromUnit;
		this.urgency = urgency;
		this.requirement = requirement;
		this.opinion = opinion;
		this.accessory = accessory;
		this.type = type;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}	
	

	public Date getSendDate() {
		return sendDate;
	}

	public void setSendDate(Date sendDate) {
		this.sendDate = sendDate;
	}

	public Date getReceiveDate() {
		return receiveDate;
	}

	public void setReceiveDate(Date receiveDate) {
		this.receiveDate = receiveDate;
	}

	public String getNo() {
		return this.no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFromUnit() {
		return this.fromUnit;
	}

	public void setFromUnit(String fromUnit) {
		this.fromUnit = fromUnit;
	}

	public String getUrgency() {
		return this.urgency;
	}

	public void setUrgency(String urgency) {
		this.urgency = urgency;
	}

	public String getRequirement() {
		return this.requirement;
	}

	public void setRequirement(String requirement) {
		this.requirement = requirement;
	}

	public String getOpinion() {
		return this.opinion;
	}

	public void setOpinion(String opinion) {
		this.opinion = opinion;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
