package hibernate;
// Generated 2017-4-13 17:12:05 by Hibernate Tools 5.1.0.Beta1

/**
 * Commonfile generated by hbm2java
 */
public class Commonfile implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private String fromUnit;
	private String no;
	private String accessory;
	private String type;

	public Commonfile() {
	}

	public Commonfile(String name, String fromUnit, String no, String accessory, String type) {
		this.name = name;
		this.fromUnit = fromUnit;
		this.no = no;
		this.accessory = accessory;
		this.type = type;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		if (this.name == null) return null;
		return this.name.replace("\"", "\\\"");
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFromUnit() {
		return this.fromUnit;
	}

	public void setFromUnit(String fromUnit) {
		this.fromUnit = fromUnit;
	}

	public String getNo() {
		return this.no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
