package hibernate;
// Generated 2017-11-19 16:44:09 by Hibernate Tools 5.2.3.Final

/**
 * Constructionelec generated by hbm2java
 */
public class Constructionelec implements java.io.Serializable {

	private Integer id;
	private String name;
	private String type;
	private String num;
	private String singlepower;
	private String sumpower;
	private String factory;
	private String shiyong;
	private String outtime;
	private String intime;
	private String plantime;
	private String realtime;
	private String status;
	private String approve;
	private String accessory;
	private String projectName;

	public Constructionelec() {
	}

	public Constructionelec(String name, String type, String num, String singlepower, String sumpower, String factory,
			String shiyong, String outtime, String intime, String plantime, String realtime, String status,
			String approve, String accessory, String projectName) {
		this.name = name;
		this.type = type;
		this.num = num;
		this.singlepower = singlepower;
		this.sumpower = sumpower;
		this.factory = factory;
		this.shiyong = shiyong;
		this.outtime = outtime;
		this.intime = intime;
		this.plantime = plantime;
		this.realtime = realtime;
		this.status = status;
		this.approve = approve;
		this.accessory = accessory;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getNum() {
		return this.num;
	}

	public void setNum(String num) {
		this.num = num;
	}

	public String getSinglepower() {
		return this.singlepower;
	}

	public void setSinglepower(String singlepower) {
		this.singlepower = singlepower;
	}

	public String getSumpower() {
		return this.sumpower;
	}

	public void setSumpower(String sumpower) {
		this.sumpower = sumpower;
	}

	public String getFactory() {
		return this.factory;
	}

	public void setFactory(String factory) {
		this.factory = factory;
	}

	public String getShiyong() {
		return this.shiyong;
	}

	public void setShiyong(String shiyong) {
		this.shiyong = shiyong;
	}

	public String getOuttime() {
		return this.outtime;
	}

	public void setOuttime(String outtime) {
		this.outtime = outtime;
	}

	public String getIntime() {
		return this.intime;
	}

	public void setIntime(String intime) {
		this.intime = intime;
	}

	public String getPlantime() {
		return this.plantime;
	}

	public void setPlantime(String plantime) {
		this.plantime = plantime;
	}

	public String getRealtime() {
		return this.realtime;
	}

	public void setRealtime(String realtime) {
		this.realtime = realtime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getApprove() {
		return this.approve;
	}

	public void setApprove(String approve) {
		this.approve = approve;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
