package hibernate;
// Generated 2017-5-23 14:36:41 by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * Daibanplanmade generated by hbm2java
 */
public class Daibanplanmade implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String holiday;
	private String planname;
	private Date bianzhitime;
	private String accessory;
	private String projectName;

	public Daibanplanmade() {
	}

	public Daibanplanmade(String holiday, String planname, Date bianzhitime, String accessory, String projectName) {
		this.holiday = holiday;
		this.planname = planname;
		this.bianzhitime = bianzhitime;
		this.accessory = accessory;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getHoliday() {
		return this.holiday;
	}

	public void setHoliday(String holiday) {
		this.holiday = holiday;
	}

	public String getPlanname() {
		return this.planname;
	}

	public void setPlanname(String planname) {
		this.planname = planname;
	}

	public Date getBianzhitime() {
		return this.bianzhitime;
	}

	public void setBianzhitime(Date bianzhitime) {
		this.bianzhitime = bianzhitime;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
