package hibernate;
// Generated 2017-3-15 10:23:35 by Hibernate Tools 5.1.0.Beta1

/**
 * Deductionstrategy generated by hbm2java
 */
public class Deductionstrategy implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String item;
	private String score;
	private String cycle;
	private String start;
	private String relateTable;
	private String relateFiled;
	private String includeFile;

	public Deductionstrategy() {
	}

	public Deductionstrategy(String item, String score, String cycle, String start, String relateTable,
			String relateFiled, String includeFile) {
		this.item = item;
		this.score = score;
		this.cycle = cycle;
		this.start = start;
		this.relateTable = relateTable;
		this.relateFiled = relateFiled;
		this.includeFile = includeFile;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getItem() {
		return this.item;
	}

	public void setItem(String item) {
		this.item = item;
	}

	public String getScore() {
		return this.score;
	}

	public void setScore(String score) {
		this.score = score;
	}

	public String getCycle() {
		return this.cycle;
	}

	public void setCycle(String cycle) {
		this.cycle = cycle;
	}

	public String getStart() {
		return this.start;
	}

	public void setStart(String start) {
		this.start = start;
	}

	public String getRelateTable() {
		return this.relateTable;
	}

	public void setRelateTable(String relateTable) {
		this.relateTable = relateTable;
	}

	public String getRelateFiled() {
		return this.relateFiled;
	}

	public void setRelateFiled(String relateFiled) {
		this.relateFiled = relateFiled;
	}

	public String getIncludeFile() {
		return this.includeFile;
	}

	public void setIncludeFile(String includeFile) {
		this.includeFile = includeFile;
	}

}
