package hibernate;
// Generated 2017-4-18 15:09:28 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * ElecEquip generated by hbm2java
 */
public class ElecEquip implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String equipNo;
	private String name;
	private String type;
	private String manuUnit;
	private String quantity;
	private String unit;
	private String purpose;
	private Date inDate;
	private String registNo;
	private String usePlace;
	private String responser;
	private String accessory;
	private String projectName;

	public ElecEquip() {
	}

	public ElecEquip(String equipNo, String name, String type, String manuUnit, String quantity, String unit,
			String purpose, Date inDate, String registNo, String usePlace, String responser, String accessory,
			String projectName) {
		this.equipNo = equipNo;
		this.name = name;
		this.type = type;
		this.manuUnit = manuUnit;
		this.quantity = quantity;
		this.unit = unit;
		this.purpose = purpose;
		this.inDate = inDate;
		this.registNo = registNo;
		this.usePlace = usePlace;
		this.responser = responser;
		this.accessory = accessory;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEquipNo() {
		return this.equipNo;
	}

	public void setEquipNo(String equipNo) {
		this.equipNo = equipNo;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getManuUnit() {
		return this.manuUnit;
	}

	public void setManuUnit(String manuUnit) {
		this.manuUnit = manuUnit;
	}

	public String getQuantity() {
		return this.quantity;
	}

	public void setQuantity(String quantity) {
		this.quantity = quantity;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public String getPurpose() {
		return this.purpose;
	}

	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}

	public Date getInDate() {
		return this.inDate;
	}

	public void setInDate(Date inDate) {
		this.inDate = inDate;
	}

	public String getRegistNo() {
		return this.registNo;
	}

	public void setRegistNo(String registNo) {
		this.registNo = registNo;
	}

	public String getUsePlace() {
		return this.usePlace;
	}

	public void setUsePlace(String usePlace) {
		this.usePlace = usePlace;
	}

	public String getResponser() {
		return this.responser;
	}

	public void setResponser(String responser) {
		this.responser = responser;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
