package hibernate;
// Generated 2017-3-7 15:30:53 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * Emepractice generated by hbm2java
 */
public class Emepractice implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Date time;
	private String content;
	private String accessory;

	public Emepractice() {
	}

	public Emepractice(Date time, String content, String accessory) {
		this.time = time;
		this.content = content;
		this.accessory = accessory;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

}
