package hibernate;
// Generated 2016-10-20 10:10:42 by Hibernate Tools 5.1.0.Beta1

/**
 * Exemplaryfile generated by hbm2java
 */
public class Exemplaryfile implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String no;
	private String name;
	private String fromUnit;
	private String howFast;
	private String fileRequire;
	private String writeOpinion;
	private String accessory;
	private String type;

	public Exemplaryfile() {
	}

	public Exemplaryfile(String no, String name, String fromUnit, String howFast, String fileRequire,
			String writeOpinion, String accessory, String type) {
		this.no = no;
		this.name = name;
		this.fromUnit = fromUnit;
		this.howFast = howFast;
		this.fileRequire = fileRequire;
		this.writeOpinion = writeOpinion;
		this.accessory = accessory;
		this.type = type;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNo() {
		return this.no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFromUnit() {
		return this.fromUnit;
	}

	public void setFromUnit(String fromUnit) {
		this.fromUnit = fromUnit;
	}

	public String getHowFast() {
		return this.howFast;
	}

	public void setHowFast(String howFast) {
		this.howFast = howFast;
	}

	public String getFileRequire() {
		return this.fileRequire;
	}

	public void setFileRequire(String fileRequire) {
		this.fileRequire = fileRequire;
	}

	public String getWriteOpinion() {
		return this.writeOpinion;
	}

	public void setWriteOpinion(String writeOpinion) {
		this.writeOpinion = writeOpinion;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
