package hibernate;
// Generated 2017-3-31 17:15:04 by Hibernate Tools 5.1.0.Final

import java.util.Date;

/**
 * Fbactivity generated by hbm2java
 */
public class Fbactivity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Date activityDate;
	private String organization;
	private String theme;
	private String accessory;
	private String projectName;

	public Fbactivity() {
	}

	public Fbactivity(Date activityDate, String organization, String theme, String accessory, String projectName) {
		this.activityDate = activityDate;
		this.organization = organization;
		this.theme = theme;
		this.accessory = accessory;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getActivityDate() {
		return this.activityDate;
	}

	public void setActivityDate(Date activityDate) {
		this.activityDate = activityDate;
	}

	public String getOrganization() {
		return this.organization;
	}

	public void setOrganization(String organization) {
		this.organization = organization;
	}

	public String getTheme() {
		return this.theme;
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
