package hibernate;
// Generated 2017-3-31 10:34:06 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * Fenbaoplan generated by hbm2java
 */
public class Fenbaoplan implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String fenbaoname;
	private String planname;
	private Date time;
	private String accessory;
	private String projectName;

	public Fenbaoplan() {
	}

	public Fenbaoplan(String fenbaoname, String planname, Date time, String accessory, String projectName) {
		this.fenbaoname = fenbaoname;
		this.planname = planname;
		this.time = time;
		this.accessory = accessory;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFenbaoname() {
		return this.fenbaoname;
	}

	public void setFenbaoname(String fenbaoname) {
		this.fenbaoname = fenbaoname;
	}

	public String getPlanname() {
		return this.planname;
	}

	public void setPlanname(String planname) {
		this.planname = planname;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
