package hibernate;
// Generated 2017-3-31 10:34:06 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * Fenbaosaftyaccounts generated by hbm2java
 */
public class Fenbaosaftyaccounts implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String subcontractor;
	private String taizhang;
	private Date checktime;
	private String accessory;
	private String costkind;
	private String costetails;
	private String amount;
	private String reportor;
	private String register;
	private String approver;
	private String remarks;
	private Date registertime;
	private String checksituation;
	private String checkperson;
	private String projectName;

	public Fenbaosaftyaccounts() {
	}

	public Fenbaosaftyaccounts(String subcontractor, String taizhang, Date checktime, String accessory, String costkind,
			String costetails, String amount, String reportor, String register, String approver, String remarks,
			Date registertime, String checksituation, String checkperson, String projectName) {
		this.subcontractor = subcontractor;
		this.taizhang = taizhang;
		this.checktime = checktime;
		this.accessory = accessory;
		this.costkind = costkind;
		this.costetails = costetails;
		this.amount = amount;
		this.reportor = reportor;
		this.register = register;
		this.approver = approver;
		this.remarks = remarks;
		this.registertime = registertime;
		this.checksituation = checksituation;
		this.checkperson = checkperson;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSubcontractor() {
		return this.subcontractor;
	}

	public void setSubcontractor(String subcontractor) {
		this.subcontractor = subcontractor;
	}

	public String getTaizhang() {
		return this.taizhang;
	}

	public void setTaizhang(String taizhang) {
		this.taizhang = taizhang;
	}

	public Date getChecktime() {
		return this.checktime;
	}

	public void setChecktime(Date checktime) {
		this.checktime = checktime;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getCostkind() {
		return this.costkind;
	}

	public void setCostkind(String costkind) {
		this.costkind = costkind;
	}

	public String getCostetails() {
		return this.costetails;
	}

	public void setCostetails(String costetails) {
		this.costetails = costetails;
	}

	public String getAmount() {
		return this.amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	public String getReportor() {
		return this.reportor;
	}

	public void setReportor(String reportor) {
		this.reportor = reportor;
	}

	public String getRegister() {
		return this.register;
	}

	public void setRegister(String register) {
		this.register = register;
	}

	public String getApprover() {
		return this.approver;
	}

	public void setApprover(String approver) {
		this.approver = approver;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Date getRegistertime() {
		return this.registertime;
	}

	public void setRegistertime(Date registertime) {
		this.registertime = registertime;
	}

	public String getChecksituation() {
		return this.checksituation;
	}

	public void setChecksituation(String checksituation) {
		this.checksituation = checksituation;
	}

	public String getCheckperson() {
		return this.checkperson;
	}

	public void setCheckperson(String checkperson) {
		this.checkperson = checkperson;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
