package hibernate;
// Generated 2017-5-12 10:13:48 by Hibernate Tools 5.2.1.Final

/**
 * Fingerprint generated by hbm2java
 */
public class Fingerprint implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private String ip;
	private String portno;

	public Fingerprint() {
	}

	public Fingerprint(String name, String ip, String portno) {
		this.name = name;
		this.ip = ip;
		this.portno = portno;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getPortno() {
		return this.portno;
	}

	public void setPortno(String portno) {
		this.portno = portno;
	}

}
