package hibernate;
// Generated 2017-4-18 10:04:40 by Hibernate Tools 5.2.0.CR1

/**
 * Firesafety generated by hbm2java
 */
public class FireSafety implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private String model;
	private String num;
	private String department;
	private String acqDate;
	private String changeDate;
	private String place;
	private String chargePerson;
	private String checkPeriodically;
	private String checkResult;
	private String projectName;

	public FireSafety() {
	}

	public FireSafety(String name, String model, String num, String department, String acqDate, String changeDate,
			String place, String chargePerson, String checkPeriodically, String checkResult, String projectName) {
		this.name = name;
		this.model = model;
		this.num = num;
		this.department = department;
		this.acqDate = acqDate;
		this.changeDate = changeDate;
		this.place = place;
		this.chargePerson = chargePerson;
		this.checkPeriodically = checkPeriodically;
		this.checkResult = checkResult;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getNum() {
		return this.num;
	}

	public void setNum(String num) {
		this.num = num;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getAcqDate() {
		return this.acqDate;
	}

	public void setAcqDate(String acqDate) {
		this.acqDate = acqDate;
	}

	public String getChangeDate() {
		return this.changeDate;
	}

	public void setChangeDate(String changeDate) {
		this.changeDate = changeDate;
	}

	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	public String getChargePerson() {
		return this.chargePerson;
	}

	public void setChargePerson(String chargePerson) {
		this.chargePerson = chargePerson;
	}

	public String getCheckPeriodically() {
		return this.checkPeriodically;
	}

	public void setCheckPeriodically(String checkPeriodically) {
		this.checkPeriodically = checkPeriodically;
	}

	public String getCheckResult() {
		return this.checkResult;
	}

	public void setCheckResult(String checkResult) {
		this.checkResult = checkResult;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
