package hibernate;
// Generated 2017-1-16 9:56:14 by Hibernate Tools 5.1.0.Beta1

/**
 * Flownode generated by hbm2java
 */
public class Flownode implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String tableId;
	private Integer stepNum;
	private Integer orderNum;
	private String nodeName;
	private Integer nodeX;
	private Integer nodeY;
	private String accessory;
	private String name;
	private String duty;
	private String phone;
	private String projectName;

	public Flownode() {
	}

	public Flownode(String tableId, Integer stepNum, Integer orderNum, String nodeName, Integer nodeX, Integer nodeY,
			String accessory, String name, String duty, String phone, String projectName) {
		this.tableId = tableId;
		this.stepNum = stepNum;
		this.orderNum = orderNum;
		this.nodeName = nodeName;
		this.nodeX = nodeX;
		this.nodeY = nodeY;
		this.accessory = accessory;
		this.name = name;
		this.duty = duty;
		this.phone = phone;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTableId() {
		return this.tableId;
	}

	public void setTableId(String tableId) {
		this.tableId = tableId;
	}

	public Integer getStepNum() {
		return this.stepNum;
	}

	public void setStepNum(Integer stepNum) {
		this.stepNum = stepNum;
	}

	public Integer getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	public String getNodeName() {
		return this.nodeName;
	}

	public void setNodeName(String nodeName) {
		this.nodeName = nodeName;
	}

	public Integer getNodeX() {
		return this.nodeX;
	}

	public void setNodeX(Integer nodeX) {
		this.nodeX = nodeX;
	}

	public Integer getNodeY() {
		return this.nodeY;
	}

	public void setNodeY(Integer nodeY) {
		this.nodeY = nodeY;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDuty() {
		return this.duty;
	}

	public void setDuty(String duty) {
		this.duty = duty;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
