package hibernate;
// Generated 2017-10-14 16:40:27 by Hibernate Tools 5.2.3.Final

/**
 * Goaldecom generated by hbm2java
 */
public class Goaldecom implements java.io.Serializable {

	private Integer id;
	private String target;
	private String goalDecom;
	private String indexValue;
	private String factor;
	private String quaSave;
	private String design;
	private String engineer;
	private String affair;
	private String buy;
	private String makeOne;
	private String examineOne;
	private String agreeOne;
	private String signOne;
	private String content;
	private String mvalue;
	private String measure;
	private String time;
	private String manager;
	private String completed;
	private String projectName;
	private String accessory;

	public Goaldecom() {
	}

	public Goaldecom(String target, String goalDecom, String indexValue, String factor, String quaSave, String design,
			String engineer, String affair, String buy, String makeOne, String examineOne, String agreeOne,
			String signOne, String content, String mvalue, String measure, String time, String manager,
			String completed, String projectName, String accessory) {
		this.target = target;
		this.goalDecom = goalDecom;
		this.indexValue = indexValue;
		this.factor = factor;
		this.quaSave = quaSave;
		this.design = design;
		this.engineer = engineer;
		this.affair = affair;
		this.buy = buy;
		this.makeOne = makeOne;
		this.examineOne = examineOne;
		this.agreeOne = agreeOne;
		this.signOne = signOne;
		this.content = content;
		this.mvalue = mvalue;
		this.measure = measure;
		this.time = time;
		this.manager = manager;
		this.completed = completed;
		this.projectName = projectName;
		this.accessory = accessory;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTarget() {
		return this.target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

	public String getGoalDecom() {
		return this.goalDecom;
	}

	public void setGoalDecom(String goalDecom) {
		this.goalDecom = goalDecom;
	}

	public String getIndexValue() {
		return this.indexValue;
	}

	public void setIndexValue(String indexValue) {
		this.indexValue = indexValue;
	}

	public String getFactor() {
		return this.factor;
	}

	public void setFactor(String factor) {
		this.factor = factor;
	}

	public String getQuaSave() {
		return this.quaSave;
	}

	public void setQuaSave(String quaSave) {
		this.quaSave = quaSave;
	}

	public String getDesign() {
		return this.design;
	}

	public void setDesign(String design) {
		this.design = design;
	}

	public String getEngineer() {
		return this.engineer;
	}

	public void setEngineer(String engineer) {
		this.engineer = engineer;
	}

	public String getAffair() {
		return this.affair;
	}

	public void setAffair(String affair) {
		this.affair = affair;
	}

	public String getBuy() {
		return this.buy;
	}

	public void setBuy(String buy) {
		this.buy = buy;
	}

	public String getMakeOne() {
		return this.makeOne;
	}

	public void setMakeOne(String makeOne) {
		this.makeOne = makeOne;
	}

	public String getExamineOne() {
		return this.examineOne;
	}

	public void setExamineOne(String examineOne) {
		this.examineOne = examineOne;
	}

	public String getAgreeOne() {
		return this.agreeOne;
	}

	public void setAgreeOne(String agreeOne) {
		this.agreeOne = agreeOne;
	}

	public String getSignOne() {
		return this.signOne;
	}

	public void setSignOne(String signOne) {
		this.signOne = signOne;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getMvalue() {
		return this.mvalue;
	}

	public void setMvalue(String mvalue) {
		this.mvalue = mvalue;
	}

	public String getMeasure() {
		return this.measure;
	}

	public void setMeasure(String measure) {
		this.measure = measure;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public String getManager() {
		return this.manager;
	}

	public void setManager(String manager) {
		this.manager = manager;
	}

	public String getCompleted() {
		return this.completed;
	}

	public void setCompleted(String completed) {
		this.completed = completed;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

}
