package hibernate;
// Generated 2017-4-18 10:59:20 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * Gongtitai generated by hbm2java
 */
public class Gongtitai implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String repoter;
	private String gangwei;
	private String name;
	private String sex;
	private Date tijiantime;
	private String tijianplace;
	private String tijianresult;
	private String type;
	private String accessory;
	private String projectName;

	public Gongtitai() {
	}

	public Gongtitai(String repoter, String gangwei, String name, String sex, Date tijiantime, String tijianplace,
			String tijianresult, String type, String accessory, String projectName) {
		this.repoter = repoter;
		this.gangwei = gangwei;
		this.name = name;
		this.sex = sex;
		this.tijiantime = tijiantime;
		this.tijianplace = tijianplace;
		this.tijianresult = tijianresult;
		this.type = type;
		this.accessory = accessory;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getRepoter() {
		return this.repoter;
	}

	public void setRepoter(String repoter) {
		this.repoter = repoter;
	}

	public String getGangwei() {
		return this.gangwei;
	}

	public void setGangwei(String gangwei) {
		this.gangwei = gangwei;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Date getTijiantime() {
		return this.tijiantime;
	}

	public void setTijiantime(Date tijiantime) {
		this.tijiantime = tijiantime;
	}

	public String getTijianplace() {
		return this.tijianplace;
	}

	public void setTijianplace(String tijianplace) {
		this.tijianplace = tijianplace;
	}

	public String getTijianresult() {
		return this.tijianresult;
	}

	public void setTijianresult(String tijianresult) {
		this.tijianresult = tijianresult;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
