package hibernate;
// Generated 2017-9-25 3:24:23 by Hibernate Tools 5.2.0.CR1

/**
 * Kaoheresult generated by hbm2java
 */
public class Kaoheresult implements java.io.Serializable {

	private Integer id;
	private Integer year;
	private String month;
	private Integer score;
	private String reason;
	private String accessory;
	private String projectName;

	public Kaoheresult() {
	}

	public Kaoheresult(Integer year, String month, Integer score, String reason, String accessory, String projectName) {
		this.year = year;
		this.month = month;
		this.score = score;
		this.reason = reason;
		this.accessory = accessory;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
