package hibernate;
// Generated 2017-3-21 10:06:14 by Hibernate Tools 5.2.0.CR1

/**
 * Koufen generated by hbm2java
 */
public class Koufen implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String koufenx;
	private String koufenzhi;
	private String koufenzq;
	private String kaoheqidian;
	private String duiykub;
	private String duiyzid;
	private String baohfile;
	private String accessory;

	public Koufen() {
	}

	public Koufen(String koufenx, String koufenzhi, String koufenzq, String kaoheqidian, String duiykub, String duiyzid,
			String baohfile, String accessory) {
		this.koufenx = koufenx;
		this.koufenzhi = koufenzhi;
		this.koufenzq = koufenzq;
		this.kaoheqidian = kaoheqidian;
		this.duiykub = duiykub;
		this.duiyzid = duiyzid;
		this.baohfile = baohfile;
		this.accessory = accessory;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getKoufenx() {
		return this.koufenx;
	}

	public void setKoufenx(String koufenx) {
		this.koufenx = koufenx;
	}

	public String getKoufenzhi() {
		return this.koufenzhi;
	}

	public void setKoufenzhi(String koufenzhi) {
		this.koufenzhi = koufenzhi;
	}

	public String getKoufenzq() {
		return this.koufenzq;
	}

	public void setKoufenzq(String koufenzq) {
		this.koufenzq = koufenzq;
	}

	public String getKaoheqidian() {
		return this.kaoheqidian;
	}

	public void setKaoheqidian(String kaoheqidian) {
		this.kaoheqidian = kaoheqidian;
	}

	public String getDuiykub() {
		return this.duiykub;
	}

	public void setDuiykub(String duiykub) {
		this.duiykub = duiykub;
	}

	public String getDuiyzid() {
		return this.duiyzid;
	}

	public void setDuiyzid(String duiyzid) {
		this.duiyzid = duiyzid;
	}

	public String getBaohfile() {
		return this.baohfile;
	}

	public void setBaohfile(String baohfile) {
		this.baohfile = baohfile;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

}
