package hibernate;
// Generated 2017-4-25 10:53:15 by Hibernate Tools 5.2.0.CR1

/**
 * Koufentongji generated by hbm2java
 */
public class Koufentongji implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String proname;
	private String koufenitem;
	private Integer koufenzhi;
	private Integer zongfen;

	public Koufentongji() {
	}

	public Koufentongji(String proname, String koufenitem, Integer koufenzhi, Integer zongfen) {
		this.proname = proname;
		this.koufenitem = koufenitem;
		this.koufenzhi = koufenzhi;
		this.zongfen = zongfen;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProname() {
		return this.proname;
	}

	public void setProname(String proname) {
		this.proname = proname;
	}

	public String getKoufenitem() {
		return this.koufenitem;
	}

	public void setKoufenitem(String koufenitem) {
		this.koufenitem = koufenitem;
	}

	public Integer getKoufenzhi() {
		return this.koufenzhi;
	}

	public void setKoufenzhi(Integer koufenzhi) {
		this.koufenzhi = koufenzhi;
	}

	public Integer getZongfen() {
		return this.zongfen;
	}

	public void setZongfen(Integer zongfen) {
		this.zongfen = zongfen;
	}

}
