package hibernate;
// Generated 2017-5-23 15:22:22 by Hibernate Tools 5.1.0.Beta1

/**
 * Managepara generated by hbm2java
 */
public class Managepara implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String content;
	private String type;
	private String quantity;
	private String unit;
	private String state;
	private String place;
	private String responsible;
	private String accessory;
	private String tableId;
	private String projectName;
	private String fbunit;

	public Managepara() {
	}

	public Managepara(String content, String type, String quantity, String unit, String state, String place,
			String responsible, String accessory, String tableId, String projectName, String fbunit) {
		this.content = content;
		this.type = type;
		this.quantity = quantity;
		this.unit = unit;
		this.state = state;
		this.place = place;
		this.responsible = responsible;
		this.accessory = accessory;
		this.tableId = tableId;
		this.projectName = projectName;
		this.fbunit = fbunit;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getQuantity() {
		return this.quantity;
	}

	public void setQuantity(String quantity) {
		this.quantity = quantity;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	public String getResponsible() {
		return this.responsible;
	}

	public void setResponsible(String responsible) {
		this.responsible = responsible;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getTableId() {
		return this.tableId;
	}

	public void setTableId(String tableId) {
		this.tableId = tableId;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getFbunit() {
		return this.fbunit;
	}

	public void setFbunit(String fbunit) {
		this.fbunit = fbunit;
	}

}
