package hibernate;
// Generated 2017-4-11 16:29:16 by Hibernate Tools 5.1.0.Final

import java.util.Date;

/**
 * Multimediafile generated by hbm2java
 */
public class Multimediafile implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Date uploadDate;
	private String accessory;
	private String type;
	private String projectName;

	public Multimediafile() {
	}

	public Multimediafile(Date uploadDate, String accessory, String type, String projectName) {
		this.uploadDate = uploadDate;
		this.accessory = accessory;
		this.type = type;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getUploadDate() {
		return this.uploadDate;
	}

	public void setUploadDate(Date uploadDate) {
		this.uploadDate = uploadDate;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
