package hibernate;
// Generated 2017-4-18 10:04:40 by Hibernate Tools 5.2.0.CR1

/**
 * Odhequipment generated by hbm2java
 */
public class ODHequipment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private String model;
	private String department;
	private String num;
	private String buyTime;
	private String serialNumber;
	private String place;
	private String responsibility;
	private String projectName;

	public ODHequipment() {
	}

	public ODHequipment(String name, String model, String department, String num, String buyTime, String serialNumber,
			String place, String responsibility, String projectName) {
		this.name = name;
		this.model = model;
		this.department = department;
		this.num = num;
		this.buyTime = buyTime;
		this.serialNumber = serialNumber;
		this.place = place;
		this.responsibility = responsibility;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getNum() {
		return this.num;
	}

	public void setNum(String num) {
		this.num = num;
	}

	public String getBuyTime() {
		return this.buyTime;
	}

	public void setBuyTime(String buyTime) {
		this.buyTime = buyTime;
	}

	public String getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	public String getResponsibility() {
		return this.responsibility;
	}

	public void setResponsibility(String responsibility) {
		this.responsibility = responsibility;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
