package hibernate;
// Generated 2017-4-18 16:06:20 by Hibernate Tools 5.2.0.CR1

/**
 * Otherjob generated by hbm2java
 */
public class Otherjob implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private String time;
	private String unit;
	private String record;
	private String accessory;
	private String projectName;

	public Otherjob() {
	}

	public Otherjob(String name, String time, String unit, String record, String accessory, String projectName) {
		this.name = name;
		this.time = time;
		this.unit = unit;
		this.record = record;
		this.accessory = accessory;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public String getRecord() {
		return this.record;
	}

	public void setRecord(String record) {
		this.record = record;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
