package hibernate;
// Generated 2017-5-18 16:10:07 by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * Periodreport generated by hbm2java
 */
public class Periodreport implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer year;
	private Integer month;
	private Integer week;
	private String accessory;
	private String type;
	private String projectName;
	private Date time;

	public Periodreport() {
	}

	public Periodreport(Integer year, Integer month, Integer week, String accessory, String type, String projectName,
			Date time) {
		this.year = year;
		this.month = month;
		this.week = week;
		this.accessory = accessory;
		this.type = type;
		this.projectName = projectName;
		this.time = time;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public Integer getMonth() {
		return this.month;
	}

	public void setMonth(Integer month) {
		this.month = month;
	}

	public Integer getWeek() {
		return this.week;
	}

	public void setWeek(Integer week) {
		this.week = week;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
