package hibernate;
// Generated 2017-4-18 10:04:40 by Hibernate Tools 5.2.0.CR1

/**
 * Podgoods generated by hbm2java
 */
public class PODgoods implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private String deliveryTime;
	private String num;
	private String personName;
	private String department;
	private String timeLimit;
	private String autograph;
	private String comment;
	private String projectName;

	public PODgoods() {
	}

	public PODgoods(String name, String deliveryTime, String num, String personName, String department,
			String timeLimit, String autograph, String comment, String projectName) {
		this.name = name;
		this.deliveryTime = deliveryTime;
		this.num = num;
		this.personName = personName;
		this.department = department;
		this.timeLimit = timeLimit;
		this.autograph = autograph;
		this.comment = comment;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDeliveryTime() {
		return this.deliveryTime;
	}

	public void setDeliveryTime(String deliveryTime) {
		this.deliveryTime = deliveryTime;
	}

	public String getNum() {
		return this.num;
	}

	public void setNum(String num) {
		this.num = num;
	}

	public String getPersonName() {
		return this.personName;
	}

	public void setPersonName(String personName) {
		this.personName = personName;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getTimeLimit() {
		return this.timeLimit;
	}

	public void setTimeLimit(String timeLimit) {
		this.timeLimit = timeLimit;
	}

	public String getAutograph() {
		return this.autograph;
	}

	public void setAutograph(String autograph) {
		this.autograph = autograph;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
