package hibernate;
// Generated 2017-4-18 10:04:40 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * Proapproval generated by hbm2java
 */
public class Proapproval implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String no;
	private String name;
	private String type;
	private String unit;
	private Date time;
	private String approval;
	private String accessory;
	private String projectName;

	public Proapproval() {
	}

	public Proapproval(String no, String name, String type, String unit, Date time, String approval, String accessory,
			String projectName) {
		this.no = no;
		this.name = name;
		this.type = type;
		this.unit = unit;
		this.time = time;
		this.approval = approval;
		this.accessory = accessory;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNo() {
		return this.no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getApproval() {
		return this.approval;
	}

	public void setApproval(String approval) {
		this.approval = approval;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
