package hibernate;
// Generated 2017-3-31 16:13:52 by Hibernate Tools 5.1.0.Final

import java.util.Date;

/**
 * Prodepartdoc generated by hbm2java
 */
public class Prodepartdoc implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String type;
	private Date uploadDate;
	private String accessory;
	private String projectName;

	public Prodepartdoc() {
	}

	public Prodepartdoc(int id) {
		this.id = id;
	}

	public Prodepartdoc(int id, String type, Date uploadDate, String accessory, String projectName) {
		this.id = id;
		this.type = type;
		this.uploadDate = uploadDate;
		this.accessory = accessory;
		this.projectName = projectName;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Date getUploadDate() {
		return this.uploadDate;
	}

	public void setUploadDate(Date uploadDate) {
		this.uploadDate = uploadDate;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
