package hibernate;

// Generated 2016-8-25 17:22:19 by Hibernate Tools 3.4.0.CR1

/**
 * Projectperson generated by hbm2java
 */
public class Projectperson implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String job;
	private String name;
	private String duty;

	public Projectperson() {
	}

	public Projectperson(String job, String name, String duty) {
		this.job = job;
		this.name = name;
		this.duty = duty;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDuty() {
		return this.duty;
	}

	public void setDuty(String duty) {
		this.duty = duty;
	}

}
