package hibernate;
// Generated 2017-1-3 11:02:56 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String no;
	private String name;
	private String scale;
	private String buildUnit;
	private String place;
	private String buildContent;
	private String manager;
	private String cost;
	private Date fileTime;
	private Date startTime;
	private String progress;
	private String accessory;

	public Project() {
	}

	public Project(String no, String name, String scale, String buildUnit, String place, String buildContent,
			String manager, String cost, Date fileTime, Date startTime, String progress, String accessory) {
		this.no = no;
		this.name = name;
		this.scale = scale;
		this.buildUnit = buildUnit;
		this.place = place;
		this.buildContent = buildContent;
		this.manager = manager;
		this.cost = cost;
		this.fileTime = fileTime;
		this.startTime = startTime;
		this.progress = progress;
		this.accessory = accessory;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNo() {
		return this.no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getScale() {
		return this.scale;
	}

	public void setScale(String scale) {
		this.scale = scale;
	}

	public String getBuildUnit() {
		return this.buildUnit;
	}

	public void setBuildUnit(String buildUnit) {
		this.buildUnit = buildUnit;
	}

	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	public String getBuildContent() {
		return this.buildContent;
	}

	public void setBuildContent(String buildContent) {
		this.buildContent = buildContent;
	}

	public String getManager() {
		return this.manager;
	}

	public void setManager(String manager) {
		this.manager = manager;
	}

	public String getCost() {
		return this.cost;
	}

	public void setCost(String cost) {
		this.cost = cost;
	}

	public Date getFileTime() {
		return this.fileTime;
	}

	public void setFileTime(Date fileTime) {
		this.fileTime = fileTime;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public String getProgress() {
		return this.progress;
	}

	public void setProgress(String progress) {
		this.progress = progress;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

}
