package hibernate;
// Generated 2017-3-31 14:34:12 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * Riskprodanger generated by hbm2java
 */
public class Riskprodanger implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String bstype;
	private Date bstime;
	private String accessory;
	private String projectName;

	public Riskprodanger() {
	}

	public Riskprodanger(String bstype, Date bstime, String accessory, String projectName) {
		this.bstype = bstype;
		this.bstime = bstime;
		this.accessory = accessory;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getBstype() {
		return this.bstype;
	}

	public void setBstype(String bstype) {
		this.bstype = bstype;
	}

	public Date getBstime() {
		return this.bstime;
	}

	public void setBstime(Date bstime) {
		this.bstime = bstime;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
