package hibernate;
// Generated 2017-3-31 14:34:12 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * Riskfenbao generated by hbm2java
 */
public class Riskfenbao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String fenbaoname;
	private Date bbtime;
	private String accessory;
	private String projectName;

	public Riskfenbao() {
	}

	public Riskfenbao(String fenbaoname, Date bbtime, String accessory, String projectName) {
		this.fenbaoname = fenbaoname;
		this.bbtime = bbtime;
		this.accessory = accessory;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFenbaoname() {
		return this.fenbaoname;
	}

	public void setFenbaoname(String fenbaoname) {
		this.fenbaoname = fenbaoname;
	}

	public Date getBbtime() {
		return this.bbtime;
	}

	public void setBbtime(Date bbtime) {
		this.bbtime = bbtime;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
