package hibernate;
// Generated 2017-4-18 10:04:40 by Hibernate Tools 5.2.0.CR1

/**
 * Safetyprotocal generated by hbm2java
 */
public class Safetyprotocal implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String type;
	private String name;
	private String date;
	private String accessory;
	private String fbname;
	private String projectName;

	public Safetyprotocal() {
	}

	public Safetyprotocal(String type, String name, String date, String accessory, String fbname, String projectName) {
		this.type = type;
		this.name = name;
		this.date = date;
		this.accessory = accessory;
		this.fbname = fbname;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getFbname() {
		return this.fbname;
	}

	public void setFbname(String fbname) {
		this.fbname = fbname;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
