package hibernate;
// Generated 2017-2-17 18:33:50 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * Safepromonitor generated by hbm2java
 */
public class Safepromonitor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String bzperson;
	private Date bztime;
	private String shperson;
	private Date shtime;
	private String pzperson;
	private Date pztime;
	private String accessory;

	public Safepromonitor() {
	}

	public Safepromonitor(String bzperson, Date bztime, String shperson, Date shtime, String pzperson, Date pztime,
			String accessory) {
		this.bzperson = bzperson;
		this.bztime = bztime;
		this.shperson = shperson;
		this.shtime = shtime;
		this.pzperson = pzperson;
		this.pztime = pztime;
		this.accessory = accessory;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getBzperson() {
		return this.bzperson;
	}

	public void setBzperson(String bzperson) {
		this.bzperson = bzperson;
	}

	public Date getBztime() {
		return this.bztime;
	}

	public void setBztime(Date bztime) {
		this.bztime = bztime;
	}

	public String getShperson() {
		return this.shperson;
	}

	public void setShperson(String shperson) {
		this.shperson = shperson;
	}

	public Date getShtime() {
		return this.shtime;
	}

	public void setShtime(Date shtime) {
		this.shtime = shtime;
	}

	public String getPzperson() {
		return this.pzperson;
	}

	public void setPzperson(String pzperson) {
		this.pzperson = pzperson;
	}

	public Date getPztime() {
		return this.pztime;
	}

	public void setPztime(Date pztime) {
		this.pztime = pztime;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

}
