package hibernate;
// Generated 2017-4-18 11:11:56 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * Safecheckrec generated by hbm2java
 */
public class Safecheckrec implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private String type;
	private String num;
	private Date thisTime;
	private Date lastTime;
	private String agent;
	private String registrant;
	private String other;
	private String accessory;
	private String tableId;
	private String projectName;

	public Safecheckrec() {
	}

	public Safecheckrec(String name, String type, String num, Date thisTime, Date lastTime, String agent,
			String registrant, String other, String accessory, String tableId, String projectName) {
		this.name = name;
		this.type = type;
		this.num = num;
		this.thisTime = thisTime;
		this.lastTime = lastTime;
		this.agent = agent;
		this.registrant = registrant;
		this.other = other;
		this.accessory = accessory;
		this.tableId = tableId;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getNum() {
		return this.num;
	}

	public void setNum(String num) {
		this.num = num;
	}

	public Date getThisTime() {
		return this.thisTime;
	}

	public void setThisTime(Date thisTime) {
		this.thisTime = thisTime;
	}

	public Date getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(Date lastTime) {
		this.lastTime = lastTime;
	}

	public String getAgent() {
		return this.agent;
	}

	public void setAgent(String agent) {
		this.agent = agent;
	}

	public String getRegistrant() {
		return this.registrant;
	}

	public void setRegistrant(String registrant) {
		this.registrant = registrant;
	}

	public String getOther() {
		return this.other;
	}

	public void setOther(String other) {
		this.other = other;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getTableId() {
		return this.tableId;
	}

	public void setTableId(String tableId) {
		this.tableId = tableId;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
