package hibernate;
// Generated 2017-5-23 10:42:48 by Hibernate Tools 5.2.0.CR1

/**
 * Saftycostplan generated by hbm2java
 */
public class Saftycostplan implements java.io.Serializable {

	private Integer id;
	private String subjectnum;
	private String costkind0;
	private String costkind1;
	private String costkind2;
	private String costkind3;
	private String costkind4;
	private String costkind5;
	private String costkind6;
	private String costkind7;
	private String costkind8;
	private String costkind9;
	private String costkind01;
	private String costkind11;
	private String costkind21;
	private String costkind31;
	private String costkind41;
	private String costkind51;
	private String costkind61;
	private String costkind71;
	private String costkind81;
	private String costkind91;
	private String costkind02;
	private String costkind12;
	private String costkind22;
	private String costkind32;
	private String costkind42;
	private String costkind52;
	private String costkind62;
	private String costkind72;
	private String costkind82;
	private String costkind92;
	private String year;
	private String costplan;
	private String costplansum;
	private String costplansum1;
	private String costplansum2;
	private String accessory;
	private String costkind;
	private String projectName;
	private String yearorfull;

	public Saftycostplan() {
	}

	public Saftycostplan(String subjectnum, String costkind0, String costkind1, String costkind2, String costkind3,
			String costkind4, String costkind5, String costkind6, String costkind7, String costkind8, String costkind9,
			String costkind01, String costkind11, String costkind21, String costkind31, String costkind41,
			String costkind51, String costkind61, String costkind71, String costkind81, String costkind91,
			String costkind02, String costkind12, String costkind22, String costkind32, String costkind42,
			String costkind52, String costkind62, String costkind72, String costkind82, String costkind92, String year,
			String costplan, String costplansum, String costplansum1, String costplansum2, String accessory,
			String costkind, String projectName, String yearorfull) {
		this.subjectnum = subjectnum;
		this.costkind0 = costkind0;
		this.costkind1 = costkind1;
		this.costkind2 = costkind2;
		this.costkind3 = costkind3;
		this.costkind4 = costkind4;
		this.costkind5 = costkind5;
		this.costkind6 = costkind6;
		this.costkind7 = costkind7;
		this.costkind8 = costkind8;
		this.costkind9 = costkind9;
		this.costkind01 = costkind01;
		this.costkind11 = costkind11;
		this.costkind21 = costkind21;
		this.costkind31 = costkind31;
		this.costkind41 = costkind41;
		this.costkind51 = costkind51;
		this.costkind61 = costkind61;
		this.costkind71 = costkind71;
		this.costkind81 = costkind81;
		this.costkind91 = costkind91;
		this.costkind02 = costkind02;
		this.costkind12 = costkind12;
		this.costkind22 = costkind22;
		this.costkind32 = costkind32;
		this.costkind42 = costkind42;
		this.costkind52 = costkind52;
		this.costkind62 = costkind62;
		this.costkind72 = costkind72;
		this.costkind82 = costkind82;
		this.costkind92 = costkind92;
		this.year = year;
		this.costplan = costplan;
		this.costplansum = costplansum;
		this.costplansum1 = costplansum1;
		this.costplansum2 = costplansum2;
		this.accessory = accessory;
		this.costkind = costkind;
		this.projectName = projectName;
		this.yearorfull = yearorfull;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSubjectnum() {
		return this.subjectnum;
	}

	public void setSubjectnum(String subjectnum) {
		this.subjectnum = subjectnum;
	}

	public String getCostkind0() {
		return this.costkind0;
	}

	public void setCostkind0(String costkind0) {
		this.costkind0 = costkind0;
	}

	public String getCostkind1() {
		return this.costkind1;
	}

	public void setCostkind1(String costkind1) {
		this.costkind1 = costkind1;
	}

	public String getCostkind2() {
		return this.costkind2;
	}

	public void setCostkind2(String costkind2) {
		this.costkind2 = costkind2;
	}

	public String getCostkind3() {
		return this.costkind3;
	}

	public void setCostkind3(String costkind3) {
		this.costkind3 = costkind3;
	}

	public String getCostkind4() {
		return this.costkind4;
	}

	public void setCostkind4(String costkind4) {
		this.costkind4 = costkind4;
	}

	public String getCostkind5() {
		return this.costkind5;
	}

	public void setCostkind5(String costkind5) {
		this.costkind5 = costkind5;
	}

	public String getCostkind6() {
		return this.costkind6;
	}

	public void setCostkind6(String costkind6) {
		this.costkind6 = costkind6;
	}

	public String getCostkind7() {
		return this.costkind7;
	}

	public void setCostkind7(String costkind7) {
		this.costkind7 = costkind7;
	}

	public String getCostkind8() {
		return this.costkind8;
	}

	public void setCostkind8(String costkind8) {
		this.costkind8 = costkind8;
	}

	public String getCostkind9() {
		return this.costkind9;
	}

	public void setCostkind9(String costkind9) {
		this.costkind9 = costkind9;
	}

	public String getCostkind01() {
		return this.costkind01;
	}

	public void setCostkind01(String costkind01) {
		this.costkind01 = costkind01;
	}

	public String getCostkind11() {
		return this.costkind11;
	}

	public void setCostkind11(String costkind11) {
		this.costkind11 = costkind11;
	}

	public String getCostkind21() {
		return this.costkind21;
	}

	public void setCostkind21(String costkind21) {
		this.costkind21 = costkind21;
	}

	public String getCostkind31() {
		return this.costkind31;
	}

	public void setCostkind31(String costkind31) {
		this.costkind31 = costkind31;
	}

	public String getCostkind41() {
		return this.costkind41;
	}

	public void setCostkind41(String costkind41) {
		this.costkind41 = costkind41;
	}

	public String getCostkind51() {
		return this.costkind51;
	}

	public void setCostkind51(String costkind51) {
		this.costkind51 = costkind51;
	}

	public String getCostkind61() {
		return this.costkind61;
	}

	public void setCostkind61(String costkind61) {
		this.costkind61 = costkind61;
	}

	public String getCostkind71() {
		return this.costkind71;
	}

	public void setCostkind71(String costkind71) {
		this.costkind71 = costkind71;
	}

	public String getCostkind81() {
		return this.costkind81;
	}

	public void setCostkind81(String costkind81) {
		this.costkind81 = costkind81;
	}

	public String getCostkind91() {
		return this.costkind91;
	}

	public void setCostkind91(String costkind91) {
		this.costkind91 = costkind91;
	}

	public String getCostkind02() {
		return this.costkind02;
	}

	public void setCostkind02(String costkind02) {
		this.costkind02 = costkind02;
	}

	public String getCostkind12() {
		return this.costkind12;
	}

	public void setCostkind12(String costkind12) {
		this.costkind12 = costkind12;
	}

	public String getCostkind22() {
		return this.costkind22;
	}

	public void setCostkind22(String costkind22) {
		this.costkind22 = costkind22;
	}

	public String getCostkind32() {
		return this.costkind32;
	}

	public void setCostkind32(String costkind32) {
		this.costkind32 = costkind32;
	}

	public String getCostkind42() {
		return this.costkind42;
	}

	public void setCostkind42(String costkind42) {
		this.costkind42 = costkind42;
	}

	public String getCostkind52() {
		return this.costkind52;
	}

	public void setCostkind52(String costkind52) {
		this.costkind52 = costkind52;
	}

	public String getCostkind62() {
		return this.costkind62;
	}

	public void setCostkind62(String costkind62) {
		this.costkind62 = costkind62;
	}

	public String getCostkind72() {
		return this.costkind72;
	}

	public void setCostkind72(String costkind72) {
		this.costkind72 = costkind72;
	}

	public String getCostkind82() {
		return this.costkind82;
	}

	public void setCostkind82(String costkind82) {
		this.costkind82 = costkind82;
	}

	public String getCostkind92() {
		return this.costkind92;
	}

	public void setCostkind92(String costkind92) {
		this.costkind92 = costkind92;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getCostplan() {
		return this.costplan;
	}

	public void setCostplan(String costplan) {
		this.costplan = costplan;
	}

	public String getCostplansum() {
		return this.costplansum;
	}

	public void setCostplansum(String costplansum) {
		this.costplansum = costplansum;
	}

	public String getCostplansum1() {
		return this.costplansum1;
	}

	public void setCostplansum1(String costplansum1) {
		this.costplansum1 = costplansum1;
	}

	public String getCostplansum2() {
		return this.costplansum2;
	}

	public void setCostplansum2(String costplansum2) {
		this.costplansum2 = costplansum2;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getCostkind() {
		return this.costkind;
	}

	public void setCostkind(String costkind) {
		this.costkind = costkind;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getYearorfull() {
		return this.yearorfull;
	}

	public void setYearorfull(String yearorfull) {
		this.yearorfull = yearorfull;
	}

}
