package hibernate;
// Generated 2017-3-31 14:34:12 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * Saftycheck generated by hbm2java
 */
public class Saftycheck implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Date checktime;
	private String checktype;
	private String checkunit;
	private String shoujianunit;
	private String checkperson;
	private String noticeandnum;
	private Integer pronum;
	private String prokind;
	private String prodegree;
	private String problem;
	private String advice;
	private Integer advicenum;
	private Date timeline;
	private String iscorrective;
	private Date replytime;
	private String replyandnum;
	private String accessory;
	private String accessory2;
	private String last;
	private String content;
	private String type;
	private String replyandver;
	private String projectName;

	public Saftycheck() {
	}

	public Saftycheck(Date checktime, String checktype, String checkunit, String shoujianunit, String checkperson,
			String noticeandnum, Integer pronum, String prokind, String prodegree, String problem, String advice,
			Integer advicenum, Date timeline, String iscorrective, Date replytime, String replyandnum, String accessory,
			String accessory2, String last, String content, String type, String replyandver, String projectName) {
		this.checktime = checktime;
		this.checktype = checktype;
		this.checkunit = checkunit;
		this.shoujianunit = shoujianunit;
		this.checkperson = checkperson;
		this.noticeandnum = noticeandnum;
		this.pronum = pronum;
		this.prokind = prokind;
		this.prodegree = prodegree;
		this.problem = problem;
		this.advice = advice;
		this.advicenum = advicenum;
		this.timeline = timeline;
		this.iscorrective = iscorrective;
		this.replytime = replytime;
		this.replyandnum = replyandnum;
		this.accessory = accessory;
		this.accessory2 = accessory2;
		this.last = last;
		this.content = content;
		this.type = type;
		this.replyandver = replyandver;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getChecktime() {
		return this.checktime;
	}

	public void setChecktime(Date checktime) {
		this.checktime = checktime;
	}

	public String getChecktype() {
		return this.checktype;
	}

	public void setChecktype(String checktype) {
		this.checktype = checktype;
	}

	public String getCheckunit() {
		return this.checkunit;
	}

	public void setCheckunit(String checkunit) {
		this.checkunit = checkunit;
	}

	public String getShoujianunit() {
		return this.shoujianunit;
	}

	public void setShoujianunit(String shoujianunit) {
		this.shoujianunit = shoujianunit;
	}

	public String getCheckperson() {
		return this.checkperson;
	}

	public void setCheckperson(String checkperson) {
		this.checkperson = checkperson;
	}

	public String getNoticeandnum() {
		return this.noticeandnum;
	}

	public void setNoticeandnum(String noticeandnum) {
		this.noticeandnum = noticeandnum;
	}

	public Integer getPronum() {
		return this.pronum;
	}

	public void setPronum(Integer pronum) {
		this.pronum = pronum;
	}

	public String getProkind() {
		return this.prokind;
	}

	public void setProkind(String prokind) {
		this.prokind = prokind;
	}

	public String getProdegree() {
		return this.prodegree;
	}

	public void setProdegree(String prodegree) {
		this.prodegree = prodegree;
	}

	public String getProblem() {
		return this.problem;
	}

	public void setProblem(String problem) {
		this.problem = problem;
	}

	public String getAdvice() {
		return this.advice;
	}

	public void setAdvice(String advice) {
		this.advice = advice;
	}

	public Integer getAdvicenum() {
		return this.advicenum;
	}

	public void setAdvicenum(Integer advicenum) {
		this.advicenum = advicenum;
	}

	public Date getTimeline() {
		return this.timeline;
	}

	public void setTimeline(Date timeline) {
		this.timeline = timeline;
	}

	public String getIscorrective() {
		return this.iscorrective;
	}

	public void setIscorrective(String iscorrective) {
		this.iscorrective = iscorrective;
	}

	public Date getReplytime() {
		return this.replytime;
	}

	public void setReplytime(Date replytime) {
		this.replytime = replytime;
	}

	public String getReplyandnum() {
		return this.replyandnum;
	}

	public void setReplyandnum(String replyandnum) {
		this.replyandnum = replyandnum;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getAccessory2() {
		return this.accessory2;
	}

	public void setAccessory2(String accessory2) {
		this.accessory2 = accessory2;
	}

	public String getLast() {
		return this.last;
	}

	public void setLast(String last) {
		this.last = last;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getReplyandver() {
		return this.replyandver;
	}

	public void setReplyandver(String replyandver) {
		this.replyandver = replyandver;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
