package hibernate;
// Generated 2017-3-31 10:34:06 by Hibernate Tools 5.2.0.CR1

/**
 * Saftycosttj1 generated by hbm2java
 */
public class Saftycosttj1 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String year;
	private String costkind0;
	private String costkind1;
	private String costkind2;
	private String costkind3;
	private String costkind4;
	private String costkind5;
	private String costkind6;
	private String costkind7;
	private String costkind8;
	private String costkind9;
	private String costkind01;
	private String costkind11;
	private String costkind21;
	private String costkind31;
	private String costkind41;
	private String costkind51;
	private String costkind61;
	private String costkind71;
	private String costkind81;
	private String costkind91;
	private String costkind02;
	private String costkind12;
	private String costkind22;
	private String costkind32;
	private String costkind42;
	private String costkind52;
	private String costkind62;
	private String costkind72;
	private String costkind82;
	private String costkind92;
	private String costkind03;
	private String costkind13;
	private String costkind23;
	private String costkind33;
	private String costkind43;
	private String costkind53;
	private String costkind63;
	private String costkind73;
	private String costkind83;
	private String costkind93;
	private String sum1;
	private String sum2;
	private String sum3;
	private String sum4;
	private String projectName;

	public Saftycosttj1() {
	}

	public Saftycosttj1(String year, String costkind0, String costkind1, String costkind2, String costkind3,
			String costkind4, String costkind5, String costkind6, String costkind7, String costkind8, String costkind9,
			String costkind01, String costkind11, String costkind21, String costkind31, String costkind41,
			String costkind51, String costkind61, String costkind71, String costkind81, String costkind91,
			String costkind02, String costkind12, String costkind22, String costkind32, String costkind42,
			String costkind52, String costkind62, String costkind72, String costkind82, String costkind92,
			String costkind03, String costkind13, String costkind23, String costkind33, String costkind43,
			String costkind53, String costkind63, String costkind73, String costkind83, String costkind93, String sum1,
			String sum2, String sum3, String sum4, String projectName) {
		this.year = year;
		this.costkind0 = costkind0;
		this.costkind1 = costkind1;
		this.costkind2 = costkind2;
		this.costkind3 = costkind3;
		this.costkind4 = costkind4;
		this.costkind5 = costkind5;
		this.costkind6 = costkind6;
		this.costkind7 = costkind7;
		this.costkind8 = costkind8;
		this.costkind9 = costkind9;
		this.costkind01 = costkind01;
		this.costkind11 = costkind11;
		this.costkind21 = costkind21;
		this.costkind31 = costkind31;
		this.costkind41 = costkind41;
		this.costkind51 = costkind51;
		this.costkind61 = costkind61;
		this.costkind71 = costkind71;
		this.costkind81 = costkind81;
		this.costkind91 = costkind91;
		this.costkind02 = costkind02;
		this.costkind12 = costkind12;
		this.costkind22 = costkind22;
		this.costkind32 = costkind32;
		this.costkind42 = costkind42;
		this.costkind52 = costkind52;
		this.costkind62 = costkind62;
		this.costkind72 = costkind72;
		this.costkind82 = costkind82;
		this.costkind92 = costkind92;
		this.costkind03 = costkind03;
		this.costkind13 = costkind13;
		this.costkind23 = costkind23;
		this.costkind33 = costkind33;
		this.costkind43 = costkind43;
		this.costkind53 = costkind53;
		this.costkind63 = costkind63;
		this.costkind73 = costkind73;
		this.costkind83 = costkind83;
		this.costkind93 = costkind93;
		this.sum1 = sum1;
		this.sum2 = sum2;
		this.sum3 = sum3;
		this.sum4 = sum4;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getCostkind0() {
		return this.costkind0;
	}

	public void setCostkind0(String costkind0) {
		this.costkind0 = costkind0;
	}

	public String getCostkind1() {
		return this.costkind1;
	}

	public void setCostkind1(String costkind1) {
		this.costkind1 = costkind1;
	}

	public String getCostkind2() {
		return this.costkind2;
	}

	public void setCostkind2(String costkind2) {
		this.costkind2 = costkind2;
	}

	public String getCostkind3() {
		return this.costkind3;
	}

	public void setCostkind3(String costkind3) {
		this.costkind3 = costkind3;
	}

	public String getCostkind4() {
		return this.costkind4;
	}

	public void setCostkind4(String costkind4) {
		this.costkind4 = costkind4;
	}

	public String getCostkind5() {
		return this.costkind5;
	}

	public void setCostkind5(String costkind5) {
		this.costkind5 = costkind5;
	}

	public String getCostkind6() {
		return this.costkind6;
	}

	public void setCostkind6(String costkind6) {
		this.costkind6 = costkind6;
	}

	public String getCostkind7() {
		return this.costkind7;
	}

	public void setCostkind7(String costkind7) {
		this.costkind7 = costkind7;
	}

	public String getCostkind8() {
		return this.costkind8;
	}

	public void setCostkind8(String costkind8) {
		this.costkind8 = costkind8;
	}

	public String getCostkind9() {
		return this.costkind9;
	}

	public void setCostkind9(String costkind9) {
		this.costkind9 = costkind9;
	}

	public String getCostkind01() {
		return this.costkind01;
	}

	public void setCostkind01(String costkind01) {
		this.costkind01 = costkind01;
	}

	public String getCostkind11() {
		return this.costkind11;
	}

	public void setCostkind11(String costkind11) {
		this.costkind11 = costkind11;
	}

	public String getCostkind21() {
		return this.costkind21;
	}

	public void setCostkind21(String costkind21) {
		this.costkind21 = costkind21;
	}

	public String getCostkind31() {
		return this.costkind31;
	}

	public void setCostkind31(String costkind31) {
		this.costkind31 = costkind31;
	}

	public String getCostkind41() {
		return this.costkind41;
	}

	public void setCostkind41(String costkind41) {
		this.costkind41 = costkind41;
	}

	public String getCostkind51() {
		return this.costkind51;
	}

	public void setCostkind51(String costkind51) {
		this.costkind51 = costkind51;
	}

	public String getCostkind61() {
		return this.costkind61;
	}

	public void setCostkind61(String costkind61) {
		this.costkind61 = costkind61;
	}

	public String getCostkind71() {
		return this.costkind71;
	}

	public void setCostkind71(String costkind71) {
		this.costkind71 = costkind71;
	}

	public String getCostkind81() {
		return this.costkind81;
	}

	public void setCostkind81(String costkind81) {
		this.costkind81 = costkind81;
	}

	public String getCostkind91() {
		return this.costkind91;
	}

	public void setCostkind91(String costkind91) {
		this.costkind91 = costkind91;
	}

	public String getCostkind02() {
		return this.costkind02;
	}

	public void setCostkind02(String costkind02) {
		this.costkind02 = costkind02;
	}

	public String getCostkind12() {
		return this.costkind12;
	}

	public void setCostkind12(String costkind12) {
		this.costkind12 = costkind12;
	}

	public String getCostkind22() {
		return this.costkind22;
	}

	public void setCostkind22(String costkind22) {
		this.costkind22 = costkind22;
	}

	public String getCostkind32() {
		return this.costkind32;
	}

	public void setCostkind32(String costkind32) {
		this.costkind32 = costkind32;
	}

	public String getCostkind42() {
		return this.costkind42;
	}

	public void setCostkind42(String costkind42) {
		this.costkind42 = costkind42;
	}

	public String getCostkind52() {
		return this.costkind52;
	}

	public void setCostkind52(String costkind52) {
		this.costkind52 = costkind52;
	}

	public String getCostkind62() {
		return this.costkind62;
	}

	public void setCostkind62(String costkind62) {
		this.costkind62 = costkind62;
	}

	public String getCostkind72() {
		return this.costkind72;
	}

	public void setCostkind72(String costkind72) {
		this.costkind72 = costkind72;
	}

	public String getCostkind82() {
		return this.costkind82;
	}

	public void setCostkind82(String costkind82) {
		this.costkind82 = costkind82;
	}

	public String getCostkind92() {
		return this.costkind92;
	}

	public void setCostkind92(String costkind92) {
		this.costkind92 = costkind92;
	}

	public String getCostkind03() {
		return this.costkind03;
	}

	public void setCostkind03(String costkind03) {
		this.costkind03 = costkind03;
	}

	public String getCostkind13() {
		return this.costkind13;
	}

	public void setCostkind13(String costkind13) {
		this.costkind13 = costkind13;
	}

	public String getCostkind23() {
		return this.costkind23;
	}

	public void setCostkind23(String costkind23) {
		this.costkind23 = costkind23;
	}

	public String getCostkind33() {
		return this.costkind33;
	}

	public void setCostkind33(String costkind33) {
		this.costkind33 = costkind33;
	}

	public String getCostkind43() {
		return this.costkind43;
	}

	public void setCostkind43(String costkind43) {
		this.costkind43 = costkind43;
	}

	public String getCostkind53() {
		return this.costkind53;
	}

	public void setCostkind53(String costkind53) {
		this.costkind53 = costkind53;
	}

	public String getCostkind63() {
		return this.costkind63;
	}

	public void setCostkind63(String costkind63) {
		this.costkind63 = costkind63;
	}

	public String getCostkind73() {
		return this.costkind73;
	}

	public void setCostkind73(String costkind73) {
		this.costkind73 = costkind73;
	}

	public String getCostkind83() {
		return this.costkind83;
	}

	public void setCostkind83(String costkind83) {
		this.costkind83 = costkind83;
	}

	public String getCostkind93() {
		return this.costkind93;
	}

	public void setCostkind93(String costkind93) {
		this.costkind93 = costkind93;
	}

	public String getSum1() {
		return this.sum1;
	}

	public void setSum1(String sum1) {
		this.sum1 = sum1;
	}

	public String getSum2() {
		return this.sum2;
	}

	public void setSum2(String sum2) {
		this.sum2 = sum2;
	}

	public String getSum3() {
		return this.sum3;
	}

	public void setSum3(String sum3) {
		this.sum3 = sum3;
	}

	public String getSum4() {
		return this.sum4;
	}

	public void setSum4(String sum4) {
		this.sum4 = sum4;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
