package hibernate;
// Generated 2017-3-31 10:34:06 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * Saftyjiancha generated by hbm2java
 */
public class Saftyjiancha implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String jcperson;
	private Date jctime;
	private String jcresult;
	private String accessory;
	private String type;
	private String projectName;

	public Saftyjiancha() {
	}

	public Saftyjiancha(String jcperson, Date jctime, String jcresult, String accessory, String type,
			String projectName) {
		this.jcperson = jcperson;
		this.jctime = jctime;
		this.jcresult = jcresult;
		this.accessory = accessory;
		this.type = type;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getJcperson() {
		return this.jcperson;
	}

	public void setJcperson(String jcperson) {
		this.jcperson = jcperson;
	}

	public Date getJctime() {
		return this.jctime;
	}

	public void setJctime(Date jctime) {
		this.jctime = jctime;
	}

	public String getJcresult() {
		return this.jcresult;
	}

	public void setJcresult(String jcresult) {
		this.jcresult = jcresult;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
