package hibernate;
// Generated 2017-3-29 16:51:41 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * Saftyworkrizhi generated by hbm2java
 */
public class Saftyworkrizhi implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Date rizhitime;
	private String weekday;
	private String qixiday;
	private String qixinight;
	private String degreeday;
	private String degreenight;
	private String windday;
	private String windnight;
	private String rizhi;
	private String workplan;
	private String accessory;
	private String projectName;

	public Saftyworkrizhi() {
	}

	public Saftyworkrizhi(Date rizhitime, String weekday, String qixiday, String qixinight, String degreeday,
			String degreenight, String windday, String windnight, String rizhi, String workplan, String accessory,
			String projectName) {
		this.rizhitime = rizhitime;
		this.weekday = weekday;
		this.qixiday = qixiday;
		this.qixinight = qixinight;
		this.degreeday = degreeday;
		this.degreenight = degreenight;
		this.windday = windday;
		this.windnight = windnight;
		this.rizhi = rizhi;
		this.workplan = workplan;
		this.accessory = accessory;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getRizhitime() {
		return this.rizhitime;
	}

	public void setRizhitime(Date rizhitime) {
		this.rizhitime = rizhitime;
	}

	public String getWeekday() {
		return this.weekday;
	}

	public void setWeekday(String weekday) {
		this.weekday = weekday;
	}

	public String getQixiday() {
		return this.qixiday;
	}

	public void setQixiday(String qixiday) {
		this.qixiday = qixiday;
	}

	public String getQixinight() {
		return this.qixinight;
	}

	public void setQixinight(String qixinight) {
		this.qixinight = qixinight;
	}

	public String getDegreeday() {
		return this.degreeday;
	}

	public void setDegreeday(String degreeday) {
		this.degreeday = degreeday;
	}

	public String getDegreenight() {
		return this.degreenight;
	}

	public void setDegreenight(String degreenight) {
		this.degreenight = degreenight;
	}

	public String getWindday() {
		return this.windday;
	}

	public void setWindday(String windday) {
		this.windday = windday;
	}

	public String getWindnight() {
		return this.windnight;
	}

	public void setWindnight(String windnight) {
		this.windnight = windnight;
	}

	public String getRizhi() {
		return this.rizhi;
	}

	public void setRizhi(String rizhi) {
		this.rizhi = rizhi;
	}

	public String getWorkplan() {
		return this.workplan;
	}

	public void setWorkplan(String workplan) {
		this.workplan = workplan;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
