package hibernate;

/**
 * Saftyproblem generated by hbm2java
 */
public class Saftyproblem implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String kind;
	private String subkind;
	private String showkind;
	private Integer score;
	private String accessory;

	public Saftyproblem() {
	}

	public Saftyproblem(Integer id, String kind, String subkind, String showkind, Integer score, String accessory) {
		super();
		this.id = id;
		this.kind = kind;
		this.subkind = subkind;
		this.showkind = showkind;
		this.score = score;
		this.accessory = accessory;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getKind() {
		return kind;
	}

	public void setKind(String kind) {
		this.kind = kind;
	}

	public String getSubkind() {
		return subkind;
	}

	public void setSubkind(String subkind) {
		this.subkind = subkind;
	}

	public String getShowkind() {
		return showkind;
	}

	public void setShowkind(String showkind) {
		this.showkind = showkind;
	}

	public Integer getScore() {
		return score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

	public String getAccessory() {
		return accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	@Override
	public String toString() {
		return "Saftyproblem [kind=" + kind + ", subkind=" + subkind + ", showkind=" + showkind + ", score=" + score
				+ "]";
	}

}
