package hibernate;
// Generated 2017-3-31 14:34:12 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * Saftycheckyearplanfb generated by hbm2java
 */
public class Saftycheckyearplanfb implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String bzunit;
	private Date bztime;
	private String bbren;
	private Date bbtime;
	private String spren;
	private Date sptime;
	private String accessory;
	private String projectName;

	public Saftycheckyearplanfb() {
	}

	public Saftycheckyearplanfb(String bzunit, Date bztime, String bbren, Date bbtime, String spren, Date sptime,
			String accessory, String projectName) {
		this.bzunit = bzunit;
		this.bztime = bztime;
		this.bbren = bbren;
		this.bbtime = bbtime;
		this.spren = spren;
		this.sptime = sptime;
		this.accessory = accessory;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getBzunit() {
		return this.bzunit;
	}

	public void setBzunit(String bzunit) {
		this.bzunit = bzunit;
	}

	public Date getBztime() {
		return this.bztime;
	}

	public void setBztime(Date bztime) {
		this.bztime = bztime;
	}

	public String getBbren() {
		return this.bbren;
	}

	public void setBbren(String bbren) {
		this.bbren = bbren;
	}

	public Date getBbtime() {
		return this.bbtime;
	}

	public void setBbtime(Date bbtime) {
		this.bbtime = bbtime;
	}

	public String getSpren() {
		return this.spren;
	}

	public void setSpren(String spren) {
		this.spren = spren;
	}

	public Date getSptime() {
		return this.sptime;
	}

	public void setSptime(Date sptime) {
		this.sptime = sptime;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
