package hibernate;

/**
 * Sanxiang generated by hbm2java
 */
public class Sanxiang implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String project;
	private String sumnum;
	private String danwei;
	private String accessory;

	public Sanxiang() {
	}

	public Sanxiang(String project, String sumnum, String danwei, String accessory) {
		this.project = project;
		this.sumnum = sumnum;
		this.danwei = danwei;
		this.accessory = accessory;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProject() {
		return this.project;
	}

	public void setProject(String project) {
		this.project = project;
	}

	public String getSumnum() {
		return this.sumnum;
	}

	public void setSumnum(String sumnum) {
		this.sumnum = sumnum;
	}

	public String getDanwei() {
		return this.danwei;
	}

	public void setDanwei(String danwei) {
		this.danwei = danwei;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

}
