package hibernate;
// Generated 2016-10-20 15:44:38 by Hibernate Tools 5.1.0.Beta1

/**
 * Saveculture generated by hbm2java
 */
public class Saveculture implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String content;
	private String type;

	public Saveculture() {
	}

	public Saveculture(String content, String type) {
		this.content = content;
		this.type = type;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
