package hibernate;
// Generated 2017-4-19 10:22:30 by Hibernate Tools 5.2.0.CR1

/**
 * Saveproduct generated by hbm2java
 */
public class Saveproduct implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String evaluateRate;
	private String trainRate;
	private String reformRate;
	private String reachRate;
	private String examineRate;
	private String enviPassRate;
	private String bottomRate;
	private String sickPassRate;
	private String checkRate;
	private String workAcci;
	private String prodAcci;
	private String acciRate;
	private String fenBaoAcci;
	private String disaster;
	private String fireAcci;
	private String jobEvent;
	private String pollutEvent;
	private String behave;
	private String timeYear;
	private String accessory;
	private String type;
	private String management;
	private String contrl;
	private String projectName;

	public Saveproduct() {
	}

	public Saveproduct(String evaluateRate, String trainRate, String reformRate, String reachRate, String examineRate,
			String enviPassRate, String bottomRate, String sickPassRate, String checkRate, String workAcci,
			String prodAcci, String acciRate, String fenBaoAcci, String disaster, String fireAcci, String jobEvent,
			String pollutEvent, String behave, String timeYear, String accessory, String type, String management,
			String contrl, String projectName) {
		this.evaluateRate = evaluateRate;
		this.trainRate = trainRate;
		this.reformRate = reformRate;
		this.reachRate = reachRate;
		this.examineRate = examineRate;
		this.enviPassRate = enviPassRate;
		this.bottomRate = bottomRate;
		this.sickPassRate = sickPassRate;
		this.checkRate = checkRate;
		this.workAcci = workAcci;
		this.prodAcci = prodAcci;
		this.acciRate = acciRate;
		this.fenBaoAcci = fenBaoAcci;
		this.disaster = disaster;
		this.fireAcci = fireAcci;
		this.jobEvent = jobEvent;
		this.pollutEvent = pollutEvent;
		this.behave = behave;
		this.timeYear = timeYear;
		this.accessory = accessory;
		this.type = type;
		this.management = management;
		this.contrl = contrl;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEvaluateRate() {
		return this.evaluateRate;
	}

	public void setEvaluateRate(String evaluateRate) {
		this.evaluateRate = evaluateRate;
	}

	public String getTrainRate() {
		return this.trainRate;
	}

	public void setTrainRate(String trainRate) {
		this.trainRate = trainRate;
	}

	public String getReformRate() {
		return this.reformRate;
	}

	public void setReformRate(String reformRate) {
		this.reformRate = reformRate;
	}

	public String getReachRate() {
		return this.reachRate;
	}

	public void setReachRate(String reachRate) {
		this.reachRate = reachRate;
	}

	public String getExamineRate() {
		return this.examineRate;
	}

	public void setExamineRate(String examineRate) {
		this.examineRate = examineRate;
	}

	public String getEnviPassRate() {
		return this.enviPassRate;
	}

	public void setEnviPassRate(String enviPassRate) {
		this.enviPassRate = enviPassRate;
	}

	public String getBottomRate() {
		return this.bottomRate;
	}

	public void setBottomRate(String bottomRate) {
		this.bottomRate = bottomRate;
	}

	public String getSickPassRate() {
		return this.sickPassRate;
	}

	public void setSickPassRate(String sickPassRate) {
		this.sickPassRate = sickPassRate;
	}

	public String getCheckRate() {
		return this.checkRate;
	}

	public void setCheckRate(String checkRate) {
		this.checkRate = checkRate;
	}

	public String getWorkAcci() {
		return this.workAcci;
	}

	public void setWorkAcci(String workAcci) {
		this.workAcci = workAcci;
	}

	public String getProdAcci() {
		return this.prodAcci;
	}

	public void setProdAcci(String prodAcci) {
		this.prodAcci = prodAcci;
	}

	public String getAcciRate() {
		return this.acciRate;
	}

	public void setAcciRate(String acciRate) {
		this.acciRate = acciRate;
	}

	public String getFenBaoAcci() {
		return this.fenBaoAcci;
	}

	public void setFenBaoAcci(String fenBaoAcci) {
		this.fenBaoAcci = fenBaoAcci;
	}

	public String getDisaster() {
		return this.disaster;
	}

	public void setDisaster(String disaster) {
		this.disaster = disaster;
	}

	public String getFireAcci() {
		return this.fireAcci;
	}

	public void setFireAcci(String fireAcci) {
		this.fireAcci = fireAcci;
	}

	public String getJobEvent() {
		return this.jobEvent;
	}

	public void setJobEvent(String jobEvent) {
		this.jobEvent = jobEvent;
	}

	public String getPollutEvent() {
		return this.pollutEvent;
	}

	public void setPollutEvent(String pollutEvent) {
		this.pollutEvent = pollutEvent;
	}

	public String getBehave() {
		return this.behave;
	}

	public void setBehave(String behave) {
		this.behave = behave;
	}

	public String getTimeYear() {
		return this.timeYear;
	}

	public void setTimeYear(String timeYear) {
		this.timeYear = timeYear;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getManagement() {
		return this.management;
	}

	public void setManagement(String management) {
		this.management = management;
	}

	public String getContrl() {
		return this.contrl;
	}

	public void setContrl(String contrl) {
		this.contrl = contrl;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
