package hibernate;
// Generated 2018-4-24 15:12:48 by Hibernate Tools 5.2.1.Final

/**
 * Saveenergyjc generated by hbm2java
 */
public class Saveenergyjc implements java.io.Serializable {

	private int id;
	private String year;
	private String season;
	private String elec;
	private String gas;
	private String hgas;
	private String date;
	private String ngas;
	private String accessory;
	private String projectName;

	public Saveenergyjc() {
	}

	public Saveenergyjc(int id) {
		this.id = id;
	}

	public Saveenergyjc(int id, String year, String season, String elec, String gas, String hgas, String date,
			String ngas, String accessory, String projectName) {
		this.id = id;
		this.year = year;
		this.season = season;
		this.elec = elec;
		this.gas = gas;
		this.hgas = hgas;
		this.date = date;
		this.ngas = ngas;
		this.accessory = accessory;
		this.projectName = projectName;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getSeason() {
		return this.season;
	}

	public void setSeason(String season) {
		this.season = season;
	}

	public String getElec() {
		return this.elec;
	}

	public void setElec(String elec) {
		this.elec = elec;
	}

	public String getGas() {
		return this.gas;
	}

	public void setGas(String gas) {
		this.gas = gas;
	}

	public String getHgas() {
		return this.hgas;
	}

	public void setHgas(String hgas) {
		this.hgas = hgas;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getNgas() {
		return this.ngas;
	}

	public void setNgas(String ngas) {
		this.ngas = ngas;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
