package hibernate;
// Generated 2017-5-22 16:37:09 by Hibernate Tools 5.2.1.Final

/**
 * Schemeimple generated by hbm2java
 */
public class Schemeimple implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String no;
	private String schemeName;
	private String supervise;
	private String acceptance;
	private String accessory;
	private String projectName;
	private String jd;

	public Schemeimple() {
	}

	public Schemeimple(String no, String schemeName, String supervise, String acceptance, String accessory,
			String projectName, String jd) {
		this.no = no;
		this.schemeName = schemeName;
		this.supervise = supervise;
		this.acceptance = acceptance;
		this.accessory = accessory;
		this.projectName = projectName;
		this.jd = jd;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNo() {
		return this.no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	public String getSchemeName() {
		return this.schemeName;
	}

	public void setSchemeName(String schemeName) {
		this.schemeName = schemeName;
	}

	public String getSupervise() {
		return this.supervise;
	}

	public void setSupervise(String supervise) {
		this.supervise = supervise;
	}

	public String getAcceptance() {
		return this.acceptance;
	}

	public void setAcceptance(String acceptance) {
		this.acceptance = acceptance;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getJd() {
		return this.jd;
	}

	public void setJd(String jd) {
		this.jd = jd;
	}

}
