package hibernate;
// Generated 2017-4-18 10:04:40 by Hibernate Tools 5.2.0.CR1

/**
 * Securejobslip generated by hbm2java
 */
public class SecureJobSlip implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String workPlace;
	private String workContent;
	private String workTime;
	private String dangerSource;
	private String principle;
	private String workerNum;
	private String accessory;
	private String projectName;

	public SecureJobSlip() {
	}

	public SecureJobSlip(String workPlace, String workContent, String workTime, String dangerSource, String principle,
			String workerNum, String accessory, String projectName) {
		this.workPlace = workPlace;
		this.workContent = workContent;
		this.workTime = workTime;
		this.dangerSource = dangerSource;
		this.principle = principle;
		this.workerNum = workerNum;
		this.accessory = accessory;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getWorkPlace() {
		return this.workPlace;
	}

	public void setWorkPlace(String workPlace) {
		this.workPlace = workPlace;
	}

	public String getWorkContent() {
		return this.workContent;
	}

	public void setWorkContent(String workContent) {
		this.workContent = workContent;
	}

	public String getWorkTime() {
		return this.workTime;
	}

	public void setWorkTime(String workTime) {
		this.workTime = workTime;
	}

	public String getDangerSource() {
		return this.dangerSource;
	}

	public void setDangerSource(String dangerSource) {
		this.dangerSource = dangerSource;
	}

	public String getPrinciple() {
		return this.principle;
	}

	public void setPrinciple(String principle) {
		this.principle = principle;
	}

	public String getWorkerNum() {
		return this.workerNum;
	}

	public void setWorkerNum(String workerNum) {
		this.workerNum = workerNum;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
