package hibernate;
// Generated 2017-5-17 10:51:49 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * Securityplan generated by hbm2java
 */
public class Securityplan implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String accessory;
	private String title;
	private String userName;
	private Date time;
	private String timeyear;
	private String fname;
	private String projectName;

	public Securityplan() {
	}

	public Securityplan(String accessory, String title, String userName, Date time, String timeyear, String fname,
			String projectName) {
		this.accessory = accessory;
		this.title = title;
		this.userName = userName;
		this.time = time;
		this.timeyear = timeyear;
		this.fname = fname;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getTimeyear() {
		return this.timeyear;
	}

	public void setTimeyear(String timeyear) {
		this.timeyear = timeyear;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
