package hibernate;
// Generated 2017-9-13 0:57:24 by Hibernate Tools 5.2.0.CR1

/**
 * Standmodel generated by hbm2java
 */
public class Standmodel implements java.io.Serializable {

	private int id;
	private String one;
	private String two;
	private String three;
	private String modelname;
	private String accessory;

	public Standmodel() {
	}

	public Standmodel(int id) {
		this.id = id;
	}

	public Standmodel(int id, String one, String two, String three, String modelname, String accessory) {
		this.id = id;
		this.one = one;
		this.two = two;
		this.three = three;
		this.modelname = modelname;
		this.accessory = accessory;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getOne() {
		return this.one;
	}

	public void setOne(String one) {
		this.one = one;
	}

	public String getTwo() {
		return this.two;
	}

	public void setTwo(String two) {
		this.two = two;
	}

	public String getThree() {
		return this.three;
	}

	public void setThree(String three) {
		this.three = three;
	}

	public String getModelname() {
		return this.modelname;
	}

	public void setModelname(String modelname) {
		this.modelname = modelname;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

}
