package hibernate;
// Generated 2017-3-31 14:34:12 by Hibernate Tools 5.2.0.CR1

/**
 * Taizhangfb generated by hbm2java
 */
public class Taizhangfb implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String fbname;
	private String year;
	private String month;
	private String accessory;
	private String projectName;

	public Taizhangfb() {
	}

	public Taizhangfb(String fbname, String year, String month, String accessory, String projectName) {
		this.fbname = fbname;
		this.year = year;
		this.month = month;
		this.accessory = accessory;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFbname() {
		return this.fbname;
	}

	public void setFbname(String fbname) {
		this.fbname = fbname;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
