package hibernate;
// Generated 2017-5-29 16:51:11 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * Taizhang generated by hbm2java
 */
public class Taizhang implements java.io.Serializable {

	private Integer id;
	private Integer no;
	private Integer checkId;
	private String problem;
	private Date solveTime;
	private String accessory;
	private String solveAcc;
	private String solveExp;
	private String solvePerson;
	private Date expTime;
	private String location;
	private String checkperson;
	private String prolevel;
	private String correction;
	private String solvedep;
	private String correctionfee;
	private String supperson;
	private String prevent;
	private String projectName;
	private String type;

	public Taizhang() {
	}

	public Taizhang(Integer no, Integer checkId, String problem, Date solveTime, String accessory, String solveAcc,
			String solveExp, String solvePerson, Date expTime, String location, String checkperson, String prolevel,
			String correction, String solvedep, String correctionfee, String supperson, String prevent,
			String projectName, String type) {
		this.no = no;
		this.checkId = checkId;
		this.problem = problem;
		this.solveTime = solveTime;
		this.accessory = accessory;
		this.solveAcc = solveAcc;
		this.solveExp = solveExp;
		this.solvePerson = solvePerson;
		this.expTime = expTime;
		this.location = location;
		this.checkperson = checkperson;
		this.prolevel = prolevel;
		this.correction = correction;
		this.solvedep = solvedep;
		this.correctionfee = correctionfee;
		this.supperson = supperson;
		this.prevent = prevent;
		this.projectName = projectName;
		this.type = type;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getNo() {
		return this.no;
	}

	public void setNo(Integer no) {
		this.no = no;
	}

	public Integer getCheckId() {
		return this.checkId;
	}

	public void setCheckId(Integer checkId) {
		this.checkId = checkId;
	}

	public String getProblem() {
		return this.problem;
	}

	public void setProblem(String problem) {
		this.problem = problem;
	}

	public Date getSolveTime() {
		return this.solveTime;
	}

	public void setSolveTime(Date solveTime) {
		this.solveTime = solveTime;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getSolveAcc() {
		return this.solveAcc;
	}

	public void setSolveAcc(String solveAcc) {
		this.solveAcc = solveAcc;
	}

	public String getSolveExp() {
		return this.solveExp;
	}

	public void setSolveExp(String solveExp) {
		this.solveExp = solveExp;
	}

	public String getSolvePerson() {
		return this.solvePerson;
	}

	public void setSolvePerson(String solvePerson) {
		this.solvePerson = solvePerson;
	}

	public Date getExpTime() {
		return this.expTime;
	}

	public void setExpTime(Date expTime) {
		this.expTime = expTime;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getCheckperson() {
		return this.checkperson;
	}

	public void setCheckperson(String checkperson) {
		this.checkperson = checkperson;
	}

	public String getProlevel() {
		return this.prolevel;
	}

	public void setProlevel(String prolevel) {
		this.prolevel = prolevel;
	}

	public String getCorrection() {
		return this.correction;
	}

	public void setCorrection(String correction) {
		this.correction = correction;
	}

	public String getSolvedep() {
		return this.solvedep;
	}

	public void setSolvedep(String solvedep) {
		this.solvedep = solvedep;
	}

	public String getCorrectionfee() {
		return this.correctionfee;
	}

	public void setCorrectionfee(String correctionfee) {
		this.correctionfee = correctionfee;
	}

	public String getSupperson() {
		return this.supperson;
	}

	public void setSupperson(String supperson) {
		this.supperson = supperson;
	}

	public String getPrevent() {
		return this.prevent;
	}

	public void setPrevent(String prevent) {
		this.prevent = prevent;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
