package hibernate;
// Generated 2017-6-16 14:50:08 by Hibernate Tools 5.1.2.Final

/**
 * Testrecord generated by hbm2java
 */
public class Testrecord implements java.io.Serializable {

	private Integer id;
	private String name;
	private String belongTo;
	private String questionIdlist1;
	private Integer questionScore1;
	private String questionIdlist2;
	private Integer questionScore2;
	private String questionIdlist3;
	private Integer questionScore3;
	private String questionIdlist4;
	private Integer questionScore4;

	public Testrecord() {
	}

	public Testrecord(String name, String belongTo, String questionIdlist1, Integer questionScore1,
			String questionIdlist2, Integer questionScore2, String questionIdlist3, Integer questionScore3,
			String questionIdlist4, Integer questionScore4) {
		this.name = name;
		this.belongTo = belongTo;
		this.questionIdlist1 = questionIdlist1;
		this.questionScore1 = questionScore1;
		this.questionIdlist2 = questionIdlist2;
		this.questionScore2 = questionScore2;
		this.questionIdlist3 = questionIdlist3;
		this.questionScore3 = questionScore3;
		this.questionIdlist4 = questionIdlist4;
		this.questionScore4 = questionScore4;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getBelongTo() {
		return this.belongTo;
	}

	public void setBelongTo(String belongTo) {
		this.belongTo = belongTo;
	}

	public String getQuestionIdlist1() {
		return this.questionIdlist1;
	}

	public void setQuestionIdlist1(String questionIdlist1) {
		this.questionIdlist1 = questionIdlist1;
	}

	public Integer getQuestionScore1() {
		return this.questionScore1;
	}

	public void setQuestionScore1(Integer questionScore1) {
		this.questionScore1 = questionScore1;
	}

	public String getQuestionIdlist2() {
		return this.questionIdlist2;
	}

	public void setQuestionIdlist2(String questionIdlist2) {
		this.questionIdlist2 = questionIdlist2;
	}

	public Integer getQuestionScore2() {
		return this.questionScore2;
	}

	public void setQuestionScore2(Integer questionScore2) {
		this.questionScore2 = questionScore2;
	}

	public String getQuestionIdlist3() {
		return this.questionIdlist3;
	}

	public void setQuestionIdlist3(String questionIdlist3) {
		this.questionIdlist3 = questionIdlist3;
	}

	public Integer getQuestionScore3() {
		return this.questionScore3;
	}

	public void setQuestionScore3(Integer questionScore3) {
		this.questionScore3 = questionScore3;
	}

	public String getQuestionIdlist4() {
		return this.questionIdlist4;
	}

	public void setQuestionIdlist4(String questionIdlist4) {
		this.questionIdlist4 = questionIdlist4;
	}

	public Integer getQuestionScore4() {
		return this.questionScore4;
	}

	public void setQuestionScore4(Integer questionScore4) {
		this.questionScore4 = questionScore4;
	}

}
