package hibernate;
// Generated 2017-3-31 17:15:04 by Hibernate Tools 5.1.0.Final

import java.util.Date;

/**
 * Traintable generated by hbm2java
 */
public class Traintable implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String content;
	private String employee;
	private String method;
	private Date trainDate;
	private Date registDate;
	private String funding;
	private String accessory;
	private String tableId;
	private String projectName;

	public Traintable() {
	}

	public Traintable(String content, String employee, String method, Date trainDate, Date registDate, String funding,
			String accessory, String tableId, String projectName) {
		this.content = content;
		this.employee = employee;
		this.method = method;
		this.trainDate = trainDate;
		this.registDate = registDate;
		this.funding = funding;
		this.accessory = accessory;
		this.tableId = tableId;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getEmployee() {
		return this.employee;
	}

	public void setEmployee(String employee) {
		this.employee = employee;
	}

	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	public Date getTrainDate() {
		return this.trainDate;
	}

	public void setTrainDate(Date trainDate) {
		this.trainDate = trainDate;
	}

	public Date getRegistDate() {
		return this.registDate;
	}

	public void setRegistDate(Date registDate) {
		this.registDate = registDate;
	}

	public String getFunding() {
		return this.funding;
	}

	public void setFunding(String funding) {
		this.funding = funding;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getTableId() {
		return this.tableId;
	}

	public void setTableId(String tableId) {
		this.tableId = tableId;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
