package hibernate;
// Generated Oct 24, 2016 8:43:19 PM by Hibernate Tools 5.1.0.Beta1

/**
 * Trainperson generated by hbm2java
 */
public class Trainperson implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private String gender;
	private String position;
	private String idno;
	private String certiType;
	private String certiNo;
	private String expDate;
	private String accessory;
	private String tableId;

	public Trainperson() {
	}

	public Trainperson(String name, String gender, String position, String idno, String certiType, String certiNo,
			String expDate, String accessory, String tableId) {
		this.name = name;
		this.gender = gender;
		this.position = position;
		this.idno = idno;
		this.certiType = certiType;
		this.certiNo = certiNo;
		this.expDate = expDate;
		this.accessory = accessory;
		this.tableId = tableId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getIdno() {
		return this.idno;
	}

	public void setIdno(String idno) {
		this.idno = idno;
	}

	public String getCertiType() {
		return this.certiType;
	}

	public void setCertiType(String certiType) {
		this.certiType = certiType;
	}

	public String getCertiNo() {
		return this.certiNo;
	}

	public void setCertiNo(String certiNo) {
		this.certiNo = certiNo;
	}

	public String getExpDate() {
		return this.expDate;
	}

	public void setExpDate(String expDate) {
		this.expDate = expDate;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getTableId() {
		return this.tableId;
	}

	public void setTableId(String tableId) {
		this.tableId = tableId;
	}

}
