package hibernate;
// Generated 2017-3-31 17:15:04 by Hibernate Tools 5.1.0.Final

import java.util.Date;

/**
 * Trainplan1 generated by hbm2java
 */
public class Trainplan1 implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String content;
	private String employee;
	private String method;
	private Date classDate;
	private String classTime;
	private String budget;
	private String result;
	private String accessory;
	private String projectName;

	public Trainplan1() {
	}

	public Trainplan1(String content, String employee, String method, Date classDate, String classTime, String budget,
			String result, String accessory, String projectName) {
		this.content = content;
		this.employee = employee;
		this.method = method;
		this.classDate = classDate;
		this.classTime = classTime;
		this.budget = budget;
		this.result = result;
		this.accessory = accessory;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getEmployee() {
		return this.employee;
	}

	public void setEmployee(String employee) {
		this.employee = employee;
	}

	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	public Date getClassDate() {
		return this.classDate;
	}

	public void setClassDate(Date classDate) {
		this.classDate = classDate;
	}

	public String getClassTime() {
		return this.classTime;
	}

	public void setClassTime(String classTime) {
		this.classTime = classTime;
	}

	public String getBudget() {
		return this.budget;
	}

	public void setBudget(String budget) {
		this.budget = budget;
	}

	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
