package hibernate;
// Generated 2017-3-31 17:03:10 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * Weixianyuan generated by hbm2java
 */
public class Weixianyuan implements java.io.Serializable {

	/**
	*
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String jobActivity;
	private String badFactor;
	private String badEvent;
	private String rank;
	private String controlAction;
	private String yijian;
	private String accessory;
	private String projectName;

	private Date jobTime;
	private String jobLocation;
	private String jobContent;
	private String mainRisk;
	private String riskRank;
	private String preAction;
	private String jobMan;
	private String jobJiandu;

	public Weixianyuan() {
		super();
	}

	public Weixianyuan(Integer id, String jobActivity, String badFactor, String badEvent, String rank,
			String controlAction, String yijian, String accessory, String projectName, Date jobTime, String jobLocation,
			String jobContent, String mainRisk, String riskRank, String preAction, String jobMan, String jobJiandu) {
		super();
		this.id = id;
		this.jobActivity = jobActivity;
		this.badFactor = badFactor;
		this.badEvent = badEvent;
		this.rank = rank;
		this.controlAction = controlAction;
		this.yijian = yijian;
		this.accessory = accessory;
		this.projectName = projectName;
		this.jobTime = jobTime;
		this.jobLocation = jobLocation;
		this.jobContent = jobContent;
		this.mainRisk = mainRisk;
		this.riskRank = riskRank;
		this.preAction = preAction;
		this.jobMan = jobMan;
		this.jobJiandu = jobJiandu;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getJobActivity() {
		return jobActivity;
	}

	public void setJobActivity(String jobActivity) {
		this.jobActivity = jobActivity;
	}

	public String getBadFactor() {
		return badFactor;
	}

	public void setBadFactor(String badFactor) {
		this.badFactor = badFactor;
	}

	public String getBadEvent() {
		return badEvent;
	}

	public void setBadEvent(String badEvent) {
		this.badEvent = badEvent;
	}

	public String getRank() {
		return rank;
	}

	public void setRank(String rank) {
		this.rank = rank;
	}

	public String getControlAction() {
		return controlAction;
	}

	public void setControlAction(String controlAction) {
		this.controlAction = controlAction;
	}

	public String getYijian() {
		return yijian;
	}

	public void setYijian(String yijian) {
		this.yijian = yijian;
	}

	public String getAccessory() {
		return accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getProjectName() {
		return projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public Date getJobTime() {
		return jobTime;
	}

	public void setJobTime(Date jobTime) {
		this.jobTime = jobTime;
	}

	public String getJobLocation() {
		return jobLocation;
	}

	public void setJobLocation(String jobLocation) {
		this.jobLocation = jobLocation;
	}

	public String getJobContent() {
		return jobContent;
	}

	public void setJobContent(String jobContent) {
		this.jobContent = jobContent;
	}

	public String getMainRisk() {
		return mainRisk;
	}

	public void setMainRisk(String mainRisk) {
		this.mainRisk = mainRisk;
	}

	public String getRiskRank() {
		return riskRank;
	}

	public void setRiskRank(String riskRank) {
		this.riskRank = riskRank;
	}

	public String getPreAction() {
		return preAction;
	}

	public void setPreAction(String preAction) {
		this.preAction = preAction;
	}

	public String getJobMan() {
		return jobMan;
	}

	public void setJobMan(String jobMan) {
		this.jobMan = jobMan;
	}

	public String getJobJiandu() {
		return jobJiandu;
	}

	public void setJobJiandu(String jobJiandu) {
		this.jobJiandu = jobJiandu;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

}
