package hibernate;
// Generated 2017-10-13 17:10:25 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Yearplan generated by hbm2java
 */
public class Yearplan implements java.io.Serializable {

	private Integer id;
	private String year;
	private String workload;
	private String completed;
	private String content;
	private Integer contentNum;
	private String manager;
	private Date planDate;
	private String realDate;
	private String accessory;
	private String no;
	private String projectName;

	public Yearplan() {
	}

	public Yearplan(String year, String workload, String completed, String content, Integer contentNum, String manager,
			Date planDate, String realDate, String accessory, String no, String projectName) {
		this.year = year;
		this.workload = workload;
		this.completed = completed;
		this.content = content;
		this.contentNum = contentNum;
		this.manager = manager;
		this.planDate = planDate;
		this.realDate = realDate;
		this.accessory = accessory;
		this.no = no;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getWorkload() {
		return this.workload;
	}

	public void setWorkload(String workload) {
		this.workload = workload;
	}

	public String getCompleted() {
		return this.completed;
	}

	public void setCompleted(String completed) {
		this.completed = completed;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Integer getContentNum() {
		return this.contentNum;
	}

	public void setContentNum(Integer contentNum) {
		this.contentNum = contentNum;
	}

	public String getManager() {
		return this.manager;
	}

	public void setManager(String manager) {
		this.manager = manager;
	}

	public Date getPlanDate() {
		return this.planDate;
	}

	public void setPlanDate(Date planDate) {
		this.planDate = planDate;
	}

	public String getRealDate() {
		return this.realDate;
	}

	public void setRealDate(String realDate) {
		this.realDate = realDate;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getNo() {
		return this.no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
