package hibernate;
// Generated 2017-4-1 20:03:49 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * Yingjipxyl generated by hbm2java
 */
public class Yingjipxyl implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String content;
	private Date peixuntime;
	private String accessory;
	private String projectName;

	public Yingjipxyl() {
	}

	public Yingjipxyl(String content, Date peixuntime, String accessory, String projectName) {
		this.content = content;
		this.peixuntime = peixuntime;
		this.accessory = accessory;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getPeixuntime() {
		return this.peixuntime;
	}

	public void setPeixuntime(Date peixuntime) {
		this.peixuntime = peixuntime;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
