package hibernate;
// Generated 2017-4-5 21:30:24 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * Yingjiyuan generated by hbm2java
 */
public class Yingjiyuan implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String zuizhiname;
	private String bianzhiren;
	private Date bianzhitime;
	private String shenheren;
	private Date shenhetime;
	private String pizhunren;
	private Date pizhuntime;
	private String accessory;
	private String projectName;

	public Yingjiyuan() {
	}

	public Yingjiyuan(String zuizhiname, String bianzhiren, Date bianzhitime, String shenheren, Date shenhetime,
			String pizhunren, Date pizhuntime, String accessory, String projectName) {
		this.zuizhiname = zuizhiname;
		this.bianzhiren = bianzhiren;
		this.bianzhitime = bianzhitime;
		this.shenheren = shenheren;
		this.shenhetime = shenhetime;
		this.pizhunren = pizhunren;
		this.pizhuntime = pizhuntime;
		this.accessory = accessory;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getZuizhiname() {
		return this.zuizhiname;
	}

	public void setZuizhiname(String zuizhiname) {
		this.zuizhiname = zuizhiname;
	}

	public String getBianzhiren() {
		return this.bianzhiren;
	}

	public void setBianzhiren(String bianzhiren) {
		this.bianzhiren = bianzhiren;
	}

	public Date getBianzhitime() {
		return this.bianzhitime;
	}

	public void setBianzhitime(Date bianzhitime) {
		this.bianzhitime = bianzhitime;
	}

	public String getShenheren() {
		return this.shenheren;
	}

	public void setShenheren(String shenheren) {
		this.shenheren = shenheren;
	}

	public Date getShenhetime() {
		return this.shenhetime;
	}

	public void setShenhetime(Date shenhetime) {
		this.shenhetime = shenhetime;
	}

	public String getPizhunren() {
		return this.pizhunren;
	}

	public void setPizhunren(String pizhunren) {
		this.pizhunren = pizhunren;
	}

	public Date getPizhuntime() {
		return this.pizhuntime;
	}

	public void setPizhuntime(Date pizhuntime) {
		this.pizhuntime = pizhuntime;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
