package hibernate;
// Generated 2017-4-1 20:03:49 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * Yingjijyzz generated by hbm2java
 */
public class Yingjijyzz implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String zuizhiname;
	private String clortz;
	private Date clortztime;
	private String fuzeren;
	private String chengyuan;
	private String gongzuojg;
	private String accessory;
	private String projectName;

	public Yingjijyzz() {
	}

	public Yingjijyzz(String zuizhiname, String clortz, Date clortztime, String fuzeren, String chengyuan,
			String gongzuojg, String accessory, String projectName) {
		this.zuizhiname = zuizhiname;
		this.clortz = clortz;
		this.clortztime = clortztime;
		this.fuzeren = fuzeren;
		this.chengyuan = chengyuan;
		this.gongzuojg = gongzuojg;
		this.accessory = accessory;
		this.projectName = projectName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getZuizhiname() {
		return this.zuizhiname;
	}

	public void setZuizhiname(String zuizhiname) {
		this.zuizhiname = zuizhiname;
	}

	public String getClortz() {
		return this.clortz;
	}

	public void setClortz(String clortz) {
		this.clortz = clortz;
	}

	public Date getClortztime() {
		return this.clortztime;
	}

	public void setClortztime(Date clortztime) {
		this.clortztime = clortztime;
	}

	public String getFuzeren() {
		return this.fuzeren;
	}

	public void setFuzeren(String fuzeren) {
		this.fuzeren = fuzeren;
	}

	public String getChengyuan() {
		return this.chengyuan;
	}

	public void setChengyuan(String chengyuan) {
		this.chengyuan = chengyuan;
	}

	public String getGongzuojg() {
		return this.gongzuojg;
	}

	public void setGongzuojg(String gongzuojg) {
		this.gongzuojg = gongzuojg;
	}

	public String getAccessory() {
		return this.accessory;
	}

	public void setAccessory(String accessory) {
		this.accessory = accessory;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

}
