package hibernate;
// Generated 2017-6-19 17:18:53 by Hibernate Tools 5.1.0.Beta1

/**
 * Zhiwenkaoqin generated by hbm2java
 */
public class Zhiwenkaoqin implements java.io.Serializable {

	private Integer id;
	private String enrollNumber;
	private String userName;
	private String verifyMode;
	private String inOutMode;
	private String time;
	private String ip;
	private String port;

	public Zhiwenkaoqin() {
	}

	public Zhiwenkaoqin(String enrollNumber, String userName, String verifyMode, String inOutMode, String time,
			String ip, String port) {
		this.enrollNumber = enrollNumber;
		this.userName = userName;
		this.verifyMode = verifyMode;
		this.inOutMode = inOutMode;
		this.time = time;
		this.ip = ip;
		this.port = port;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEnrollNumber() {
		return this.enrollNumber;
	}

	public void setEnrollNumber(String enrollNumber) {
		this.enrollNumber = enrollNumber;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getVerifyMode() {
		return this.verifyMode;
	}

	public void setVerifyMode(String verifyMode) {
		this.verifyMode = verifyMode;
	}

	public String getInOutMode() {
		return this.inOutMode;
	}

	public void setInOutMode(String inOutMode) {
		this.inOutMode = inOutMode;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getPort() {
		return this.port;
	}

	public void setPort(String port) {
		this.port = port;
	}

}
