package hibernate;
// Generated 2017-6-19 17:45:20 by Hibernate Tools 5.1.0.Beta1

/**
 * Zhiwenuserinfo generated by hbm2java
 */
public class Zhiwenuserinfo implements java.io.Serializable {

	private Integer id;
	private String enrollNumber;
	private String name;
	private String password;
	private String privilege;
	private String enabled;
	private String ip;
	private String port;

	public Zhiwenuserinfo() {
	}

	public Zhiwenuserinfo(String enrollNumber, String name, String password, String privilege, String enabled,
			String ip, String port) {
		this.enrollNumber = enrollNumber;
		this.name = name;
		this.password = password;
		this.privilege = privilege;
		this.enabled = enabled;
		this.ip = ip;
		this.port = port;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEnrollNumber() {
		return this.enrollNumber;
	}

	public void setEnrollNumber(String enrollNumber) {
		this.enrollNumber = enrollNumber;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPrivilege() {
		return this.privilege;
	}

	public void setPrivilege(String privilege) {
		this.privilege = privilege;
	}

	public String getEnabled() {
		return this.enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getPort() {
		return this.port;
	}

	public void setPort(String port) {
		this.port = port;
	}

}
